/**
 * @vetios/ai-core — Inference Orchestrator (Refactor v2)
 *
 * Replaces runInference() in apps/web/lib/ai/provider.ts.
 * Drop-in compatible: accepts the same InferenceInput shape,
 * returns output_payload that goes directly into ai_inference_events.
 *
 * Pipeline:
 *   1. Input normalisation + symptom extraction
 *   2. Contradiction detection (Fix 4) — gates abstention
 *   3. LLM diagnosis model call (Fix 5: what is it?)
 *   4. ML severity model call (Fix 5: how dangerous?)
 *   5. Emergency rule override layer (Fix 2 + 3)
 *   6. Differential re-ranking (GDV promotion if rule fired)
 *   7. Confidence penalty for contradictions and overrides
 *   8. Telemetry emission
 *   9. Output assembly (backward-compatible schema v2)
 *
 * Backward compatibility guarantees:
 *   - inference_event_id: unchanged (generated by logInference, not here)
 *   - output_payload.analysis: preserved
 *   - output_payload.recommendations: preserved
 *   - output_payload.confidence_score: preserved
 *   - All new fields are additive (schema_version: '2.0' signals v2)
 */

import type {
    VetIOSInferenceOutput,
    VetIOSInputSignature,
    DiagnosisOutput,
    SeverityOutput,
    ContradictionOutput,
    Differential,
    EmergencyLevel,
    ConditionClass,
} from '../domain/types';

import {
    VetIOSInferenceOutputSchema,
    CONDITION_CLASS_LABELS,
    EMERGENCY_LEVEL_DESCRIPTIONS,
    EMERGENCY_TRIAGE_CLASSES,
} from '../domain/types';

import {
    evaluateEmergencyRules,
    riskScoreToLevel,
    maxLevel,
    LEVEL_TO_EFFECTIVE_SCORE,
} from '../domain/emergencyRules';

import { detectContradictions } from '../domain/contradictionEngine';

// ─── Provider Config ──────────────────────────────────────────────────────────

interface LLMConfig {
    apiKey:    string;
    baseUrl:   string;
    model:     string;
    timeoutMs: number;
}

function getLLMConfig(modelOverride?: string): LLMConfig {
    const key = process.env.OPENAI_API_KEY || process.env.AI_PROVIDER_API_KEY;
    if (!key) throw new Error('Missing AI provider key: set OPENAI_API_KEY or AI_PROVIDER_API_KEY.');
    return {
        apiKey:    key,
        baseUrl:   process.env.AI_PROVIDER_BASE_URL || 'https://api.openai.com/v1',
        model:     modelOverride || process.env.AI_PROVIDER_DEFAULT_MODEL || 'gpt-4o-mini',
        timeoutMs: 45_000,
    };
}

// ─── ML Severity Client ───────────────────────────────────────────────────────

interface MLSeverityResponse {
    risk_score:      number;
    confidence:      number;
    abstain:         boolean;
    model_version:   string;
    _fallback?:      boolean;
}

async function callMLSeverityModel(
    species: string,
    decisionCount: number,
    overrideCount: number,
): Promise<MLSeverityResponse> {
    const mlUrl = process.env.ML_SERVER_URL || 'http://localhost:8000';
    const timeoutMs = Number(process.env.ML_TIMEOUT_MS) || 5000;

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    try {
        const res = await fetch(`${mlUrl}/predict`, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    JSON.stringify({ decision_count: decisionCount, override_count: overrideCount, species }),
            signal:  controller.signal,
        });
        clearTimeout(timer);
        if (!res.ok) throw new Error(`ML server ${res.status}`);
        return await res.json() as MLSeverityResponse;
    } catch {
        clearTimeout(timer);
        // Graceful fallback — never block inference on ML unavailability
        return { risk_score: 0.5, confidence: 0.0, abstain: true, model_version: 'fallback', _fallback: true };
    }
}

// ─── LLM Diagnosis Call ───────────────────────────────────────────────────────

const DIAGNOSIS_SYSTEM_PROMPT = `You are VetIOS Decision Intelligence, a clinical decision support system for veterinary medicine.

YOUR ROLE:
- Provide evidence-based differential diagnoses ranked by likelihood.
- You are ADVISORY only. All outputs are for a licensed veterinarian to review.
- NEVER present output as definitive diagnosis.

CRITICAL TAXONOMY RULE — condition_class must reflect the PRIMARY pathophysiological mechanism:
- GDV, torsion, obstruction, urethral blockage, fracture, pneumothorax → "mechanical_emergency"
- Bacteraemia, viral, fungal, parasitic infection → "infectious"
- IMHA, IBD, immune-mediated polyarthritis → "inflammatory_autoimmune"
- DKA, hepatic disease, toxin, electrolyte disorder → "metabolic_toxic"
- Tumour, mass, paraneoplastic syndrome → "neoplastic"
- Heart failure, haemorrhage, septic shock → "cardiovascular_shock"
DO NOT label surgical emergencies as infectious.

RESPOND ONLY WITH VALID JSON matching the exact schema below. No markdown, no preamble.`;

const DIAGNOSIS_OUTPUT_SCHEMA = `{
  "primary_condition_class": "mechanical_emergency|infectious|inflammatory_autoimmune|metabolic_toxic|neoplastic|cardiovascular_shock",
  "primary_condition_class_rationale": "string — explain WHY this class was chosen",
  "top_differentials": [
    {
      "diagnosis": "string",
      "icd_code": "string|null",
      "condition_class": "same enum",
      "likelihood": "high|medium|low",
      "probability": 0.0,
      "rationale": "string — cite specific symptoms and patient factors",
      "supporting_symptoms": ["snake_case_symptom_key"],
      "recommended_tests": ["string"],
      "emergency_level": "CRITICAL|HIGH|MODERATE|LOW",
      "requires_surgical_consult": true
    }
  ],
  "key_symptoms_identified": ["snake_case"],
  "additional_data_needed": ["string"],
  "diagnosis_confidence": 0.0,
  "confidence_note": "string",
  "analysis": "string — overall clinical narrative",
  "recommendations": ["string"],
  "uncertainty_notes": ["string"]
}`;

async function callLLMDiagnosisModel(
    inputSignature: VetIOSInputSignature,
    config: LLMConfig,
): Promise<Record<string, unknown>> {
    const patientContext = [
        inputSignature.species   && `Species: ${inputSignature.species}`,
        inputSignature.breed     && `Breed: ${inputSignature.breed}`,
        inputSignature.weight_kg && `Weight: ${inputSignature.weight_kg} kg`,
        inputSignature.age_description && `Age: ${inputSignature.age_description}`,
        inputSignature.onset     && `Onset: ${inputSignature.onset}`,
        inputSignature.onset_hours && `Onset hours ago: ${inputSignature.onset_hours}`,
    ].filter(Boolean).join('\n');

    const symptomList = (inputSignature.symptoms || []).join(', ') || 'None specified';
    const contextList = (inputSignature.context_flags || []).join(', ') || 'None';

    const userPrompt = `PATIENT CONTEXT:\n${patientContext}

SYMPTOMS (normalised keys): ${symptomList}
CONTEXT FLAGS: ${contextList}
METADATA: ${JSON.stringify(inputSignature.metadata || {}, null, 2)}

Respond with JSON matching this schema exactly:
${DIAGNOSIS_OUTPUT_SCHEMA}`;

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), config.timeoutMs);

    try {
        const res = await fetch(`${config.baseUrl}/chat/completions`, {
            method:  'POST',
            headers: {
                'Content-Type':  'application/json',
                'Authorization': `Bearer ${config.apiKey}`,
            },
            body: JSON.stringify({
                model:           config.model,
                messages: [
                    { role: 'system', content: DIAGNOSIS_SYSTEM_PROMPT },
                    { role: 'user',   content: userPrompt },
                ],
                temperature:     0.2,
                max_tokens:      3000,
                response_format: { type: 'json_object' },
            }),
            signal: controller.signal,
        });
        clearTimeout(timer);

        if (!res.ok) {
            const body = await res.text();
            throw new Error(`LLM API ${res.status}: ${body}`);
        }

        const json = await res.json() as { choices: Array<{ message: { content: string } }> };
        const content = json.choices[0]?.message?.content ?? '{}';

        try {
            return JSON.parse(content) as Record<string, unknown>;
        } catch {
            return { raw: content, parse_error: true };
        }
    } catch (err) {
        clearTimeout(timer);
        throw err;
    }
}

// ─── Output Assemblers ────────────────────────────────────────────────────────

function assembleDiagnosisOutput(
    llmOutput: Record<string, unknown>,
    modelVersion: string,
): DiagnosisOutput {
    const primaryClass = (llmOutput['primary_condition_class'] as ConditionClass) || 'infectious';
    const rawDiffs = (llmOutput['top_differentials'] as unknown[]) || [];

    const differentials: Differential[] = rawDiffs
        .slice(0, 5)
        .map((d: unknown): Differential => {
            const diff = d as Record<string, unknown>;
            const cls = (diff['condition_class'] as ConditionClass) || primaryClass;
            return {
                diagnosis:               String(diff['diagnosis'] || 'Unknown'),
                icd_code:                (diff['icd_code'] as string) ?? null,
                condition_class:         cls,
                condition_class_label:   CONDITION_CLASS_LABELS[cls] || cls,
                likelihood:              (diff['likelihood'] as 'high' | 'medium' | 'low') || 'low',
                probability:             Number(diff['probability'] || 0),
                rationale:               String(diff['rationale'] || ''),
                supporting_symptoms:     (diff['supporting_symptoms'] as string[]) || [],
                recommended_tests:       (diff['recommended_tests'] as string[]) || [],
                emergency_level:         (diff['emergency_level'] as EmergencyLevel) || 'LOW',
                requires_surgical_consult: Boolean(diff['requires_surgical_consult']),
            };
        });

    return {
        primary_condition_class:             primaryClass,
        primary_condition_class_label:       CONDITION_CLASS_LABELS[primaryClass] || primaryClass,
        primary_condition_class_probability: Number(llmOutput['primary_condition_class_probability'] || 0.6),
        primary_condition_class_rationale:   String(llmOutput['primary_condition_class_rationale'] || ''),
        top_differentials:                   differentials,
        key_symptoms_identified:             (llmOutput['key_symptoms_identified'] as string[]) || [],
        additional_data_needed:              (llmOutput['additional_data_needed'] as string[]) || [],
        diagnosis_confidence:                Number(llmOutput['diagnosis_confidence'] || 0.5),
        confidence_note:                     String(llmOutput['confidence_note'] || ''),
        model_version:                       modelVersion,
    };
}

function assembleSeverityOutput(
    mlResponse: MLSeverityResponse,
    ruleResult: ReturnType<typeof evaluateEmergencyRules>,
    baseLevel: EmergencyLevel,
): SeverityOutput {
    const effectiveLevel = ruleResult.fired
        ? maxLevel(baseLevel, ruleResult.min_emergency_level!)
        : baseLevel;

    const effectiveScore = ruleResult.fired
        ? Math.max(LEVEL_TO_EFFECTIVE_SCORE[ruleResult.min_emergency_level!], mlResponse.risk_score)
        : mlResponse.risk_score;

    return {
        emergency_level:             effectiveLevel,
        emergency_level_description: EMERGENCY_LEVEL_DESCRIPTIONS[effectiveLevel],
        raw_risk_score:              mlResponse.risk_score,
        effective_risk_score:        effectiveScore,
        override_applied:            ruleResult.fired,
        override_pattern_id:         ruleResult.rule_id,
        override_rationale:          ruleResult.clinician_rationale,
        severity_confidence:         mlResponse._fallback ? 0.0 : mlResponse.confidence,
        model_version:               mlResponse.model_version,
    };
}

/**
 * Re-ranks differentials to promote a specific diagnosis to rank 1.
 * If the diagnosis is not present, inserts a stub at rank 1.
 */
function promoteDifferential(
    differentials: Differential[],
    promoteDiagnosis: string,
    conditionClass: ConditionClass,
    emergencyLevel: EmergencyLevel,
): Differential[] {
    const existing = differentials.findIndex(
        (d) => d.diagnosis.toLowerCase().includes(promoteDiagnosis.toLowerCase()),
    );

    let updated = [...differentials];

    if (existing >= 0) {
        // Promote existing entry
        const [promoted] = updated.splice(existing, 1);
        updated = [
            {
                ...promoted,
                likelihood:     'high',
                emergency_level: emergencyLevel,
                condition_class: conditionClass,
                condition_class_label: CONDITION_CLASS_LABELS[conditionClass],
            },
            ...updated,
        ];
    } else {
        // Insert stub — LLM didn't include it, rule demands it
        const stub: Differential = {
            diagnosis:               promoteDiagnosis,
            icd_code:                null,
            condition_class:         conditionClass,
            condition_class_label:   CONDITION_CLASS_LABELS[conditionClass],
            likelihood:              'high',
            probability:             0.85,
            rationale:               `Emergency rule '${promoteDiagnosis}' pattern matched. This diagnosis has been promoted by the emergency override system based on high-specificity symptom combination. Clinical confirmation required.`,
            supporting_symptoms:     [],
            recommended_tests:       ['Physical examination', 'Lateral abdominal radiograph', 'IV catheter placement', 'PCV/TP'],
            emergency_level:         emergencyLevel,
            requires_surgical_consult: true,
        };
        updated = [stub, ...updated].slice(0, 5);
    }

    return updated;
}

// ─── Confidence Penalty ───────────────────────────────────────────────────────

function applyConfidencePenalty(
    baseConfidence: number,
    contradiction: ContradictionOutput,
    overrideApplied: boolean,
): { penalised: number; penaltyApplied: boolean; penaltyAmount: number } {
    let penalty = 0;

    // Contradiction penalty: proportional to contradiction score
    penalty += contradiction.contradiction_score * 0.25;

    // Override penalty: if the rule had to fire, ML model was wrong
    if (overrideApplied) penalty += 0.15;

    const penaltyApplied = penalty > 0.01;
    const penalised = Math.max(0, Math.min(1, baseConfidence - penalty));

    return {
        penalised,
        penaltyApplied,
        penaltyAmount: Math.round(penalty * 1000) / 1000,
    };
}

// ─── Main Orchestrator ────────────────────────────────────────────────────────

export interface OrchestratorInput {
    model?:           string;
    input_signature:  Record<string, unknown>;
}

export interface OrchestratorOutput {
    output_payload:      VetIOSInferenceOutput;
    confidence_score:    number | null;
    uncertainty_metrics: Record<string, unknown> | null;
    raw_content:         string;
}

/**
 * Main inference orchestrator.
 *
 * Drop-in replacement for runInference() in apps/web/lib/ai/provider.ts.
 * The returned output_payload is written directly to ai_inference_events.output_payload.
 */
export async function runVetIOSInference(
    input: OrchestratorInput,
): Promise<OrchestratorOutput> {
    const pipelineStart = Date.now();
    const config = getLLMConfig(input.model);

    // ── 1: Normalise input ────────────────────────────────────────────────────
    const sig = input.input_signature as VetIOSInputSignature;
    const symptoms       = (sig.symptoms       || []).map(normaliseKey);
    const contextFlags   = [
        ...(sig.context_flags || []).map(normaliseKey),
        ...(sig.onset ? [sig.onset] : []),
        ...(sig.breed ? [normaliseKey(sig.breed)] : []),
    ];
    const symptomWeights = sig.symptom_weights;
    const species        = sig.species || 'canine';

    // ── 2: Contradiction detection (Fix 4) ────────────────────────────────────
    const contradiction = detectContradictions(symptoms, symptomWeights);

    // ── 3: LLM diagnosis model (parallel with ML severity) ───────────────────
    const [llmOutput, mlResponse] = await Promise.all([
        callLLMDiagnosisModel(sig, config),
        callMLSeverityModel(species, 1, 0),
    ]);

    // ── 4: Emergency rule evaluation (Fix 2) ─────────────────────────────────
    const ruleResult = evaluateEmergencyRules(symptoms, contextFlags);

    // ── 5: Assemble diagnosis output (Fix 1 + 5) ─────────────────────────────
    let diagnosisOutput = assembleDiagnosisOutput(llmOutput, config.model);

    // ── 6: Differential re-ranking if rule fired (Fix 2 hardcoded rule) ──────
    if (ruleResult.fired && ruleResult.promoted_diagnosis && ruleResult.min_emergency_level) {
        const cls = (EMERGENCY_TRIAGE_CLASSES.has(diagnosisOutput.primary_condition_class)
            ? diagnosisOutput.primary_condition_class
            : 'mechanical_emergency') as ConditionClass;

        diagnosisOutput = {
            ...diagnosisOutput,
            primary_condition_class:       cls,
            primary_condition_class_label: CONDITION_CLASS_LABELS[cls],
            primary_condition_class_rationale:
                ruleResult.clinician_rationale ??
                diagnosisOutput.primary_condition_class_rationale,
            top_differentials: promoteDifferential(
                diagnosisOutput.top_differentials,
                ruleResult.promoted_diagnosis,
                cls,
                ruleResult.min_emergency_level,
            ),
        };
    }

    // ── 7: Severity output (Fix 3 + 5) ───────────────────────────────────────
    const mlBaseLevel = riskScoreToLevel(mlResponse.risk_score);
    const severityOutput: SeverityOutput = assembleSeverityOutput(
        mlResponse, ruleResult, mlBaseLevel,
    );

    // ── 8: Top-level emergency level = max of diagnosis differentials + severity
    const topDiffLevel = diagnosisOutput.top_differentials[0]?.emergency_level ?? 'LOW';
    const emergencyLevel: EmergencyLevel = maxLevel(
        severityOutput.emergency_level, topDiffLevel,
    );

    // ── 9: Confidence penalty ─────────────────────────────────────────────────
    const baseConf = diagnosisOutput.diagnosis_confidence;
    const { penalised: penalisedConf, penaltyApplied, penaltyAmount } =
        applyConfidencePenalty(baseConf, contradiction, ruleResult.fired);

    // ── 10: Abstain = contradiction says so OR ML says so ────────────────────
    const abstain = contradiction.should_abstain || (mlResponse.abstain && mlResponse._fallback !== true);

    // ── 11: Telemetry ─────────────────────────────────────────────────────────
    const pipelineLatency = Date.now() - pipelineStart;

    const telemetry = {
        override_fired:              ruleResult.fired,
        override_pattern_id:         ruleResult.rule_id,
        contradiction_score:         contradiction.contradiction_score,
        abstain_recommended:         abstain,
        confidence_penalty_applied:  penaltyApplied,
        confidence_penalty_amount:   penaltyAmount,
        diagnosis_model_version:     config.model,
        severity_model_version:      mlResponse.model_version,
        pipeline_latency_ms:         pipelineLatency,
    };

    // Log to console for telemetry pipeline pickup
    if (ruleResult.fired) {
        console.warn('[VetIOS][TELEMETRY][OVERRIDE]', JSON.stringify({
            rule_id:        ruleResult.rule_id,
            rule_name:      ruleResult.rule_name,
            emergency_level: severityOutput.emergency_level,
            matched_symptoms: ruleResult.matched_symptoms,
            matched_context:  ruleResult.matched_context,
            timestamp:      new Date().toISOString(),
        }));
    }

    if (contradiction.contradiction_score > 0.1) {
        console.warn('[VetIOS][TELEMETRY][CONTRADICTION]', JSON.stringify({
            score:    contradiction.contradiction_score,
            abstain:  abstain,
            conflicts: contradiction.active_conflicts.map((c) => ({
                pair: `${c.symptom_a}↔${c.symptom_b}`,
                weight: c.conflict_weight,
            })),
            timestamp: new Date().toISOString(),
        }));
    }

    if (penaltyApplied) {
        console.warn('[VetIOS][TELEMETRY][CONFIDENCE_PENALTY]', JSON.stringify({
            base_confidence:     baseConf,
            penalised_confidence: penalisedConf,
            penalty_amount:      penaltyAmount,
            timestamp:           new Date().toISOString(),
        }));
    }

    // ── 12: Assemble final output ─────────────────────────────────────────────
    const output: VetIOSInferenceOutput = {
        schema_version:       '2.0',
        diagnosis:            diagnosisOutput,
        severity:             severityOutput,
        contradiction:        contradiction,
        emergency_level:      emergencyLevel,
        abstain:              abstain,
        contradiction_score:  contradiction.contradiction_score,
        top_differentials:    diagnosisOutput.top_differentials.slice(0, 3),
        // Legacy fields — backward compatible
        analysis:             String(llmOutput['analysis'] || ''),
        recommendations:      (llmOutput['recommendations'] as string[]) || [],
        confidence_score:     penalisedConf,
        uncertainty_notes:    (llmOutput['uncertainty_notes'] as string[]) || [],
        telemetry,
    };

    // Validate against schema — throws in dev, warns in prod
    const validated = VetIOSInferenceOutputSchema.safeParse(output);
    if (!validated.success) {
        console.error('[VetIOS][SCHEMA_VALIDATION_FAILED]', validated.error.issues);
        // Return unvalidated in production to not break the inference event
    }

    const uncertaintyMetrics: Record<string, unknown> = {
        notes:               (llmOutput['uncertainty_notes'] as string[]) || [],
        contradiction_score: contradiction.contradiction_score,
        override_applied:    ruleResult.fired,
        abstain:             abstain,
    };

    return {
        output_payload:      output,
        confidence_score:    penalisedConf,
        uncertainty_metrics: uncertaintyMetrics,
        raw_content:         JSON.stringify(output),
    };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function normaliseKey(s: string): string {
    return s.toLowerCase().replace(/[\s-]+/g, '_');
}
