export interface SoapDifferential {
    label: string;
    probability: number;
    urgency: string;
}

export interface SoapInferenceResult {
    inference_event_id: string;
    differentials: SoapDifferential[];
    confidence: number;
    recommended_tests: string[];
    cire?: {
        phi_hat?: number;
        cps?: number;
        safety_state?: string;
    } | null;
}

export interface SoapCaseInput {
    species?: string | null;
    breed?: string | null;
    age_years?: number | null;
    sex?: string | null;
    presenting_complaint?: string | null;
    symptoms?: string[] | null;
    duration_text?: string | null;
    severity?: string | null;
    history?: string | null;
    labs?: Record<string, unknown> | null;
}

export function generateSOAP(inferenceResult: SoapInferenceResult, caseInput: SoapCaseInput): string {
    const phi = inferenceResult.cire?.phi_hat ?? inferenceResult.confidence;
    const patient = [
        caseInput.species ?? 'Unknown species',
        caseInput.breed,
        caseInput.age_years == null ? null : `${caseInput.age_years} years`,
        caseInput.sex,
    ].filter(Boolean).join(' - ');
    const symptoms = caseInput.symptoms?.length
        ? caseInput.symptoms.join(', ')
        : caseInput.presenting_complaint ?? 'Not recorded';
    const tests = inferenceResult.recommended_tests.length > 0
        ? inferenceResult.recommended_tests.map((test) => `  [ ] ${formatSoapLabel(test)}`).join('\n')
        : '  [ ] Add confirmatory diagnostics based on clinician assessment.';

    return `
SOAP NOTE - Generated by VetIOS
Date: ${new Date().toLocaleDateString()}
Case ID: ${inferenceResult.inference_event_id.slice(-8).toUpperCase()}

SUBJECTIVE
Patient: ${patient || 'Not recorded'}
Chief complaint: ${caseInput.presenting_complaint ?? symptoms}
Duration: ${caseInput.duration_text ?? 'Not specified'}
Severity: ${caseInput.severity ?? 'Not specified'}
History: ${caseInput.history ?? 'No additional history recorded.'}

OBJECTIVE
${formatLabs(caseInput.labs)}

ASSESSMENT
Differential diagnoses (AI-assisted, VetIOS):
${inferenceResult.differentials.map((entry, index) =>
        `  ${index + 1}. ${formatSoapLabel(entry.label)} - ${Math.round(entry.probability * 100)}% probability [${entry.urgency.toUpperCase()}]`
    ).join('\n') || '  No ranked differential was available.'}

Reliability: ${phiHatToLabel(phi)} (phi ${phi.toFixed(2)})
Overall confidence: ${Math.round(inferenceResult.confidence * 100)}%

PLAN
Recommended diagnostics:
${tests}

Clinician to complete: treatment plan, medications, discharge instructions, and follow-up schedule.

Generated by VetIOS AI. Clinical judgment of the attending veterinarian applies.
Case reference: ${inferenceResult.inference_event_id.slice(-8).toUpperCase()}
`.trim();
}

function formatLabs(labs: Record<string, unknown> | null | undefined): string {
    const entries = Object.entries(labs ?? {})
        .filter(([, value]) => value !== null && value !== undefined && value !== '');

    if (entries.length === 0) return 'No laboratory values recorded.';

    return entries
        .map(([key, value]) => `  ${formatSoapLabel(key)}: ${String(value)}`)
        .join('\n');
}

function phiHatToLabel(phi: number): string {
    if (phi >= 0.75) return 'High reliability';
    if (phi >= 0.5) return 'Moderate reliability';
    return 'Low reliability - additional diagnostics recommended';
}

function formatSoapLabel(value: string): string {
    return value
        .replace(/[_-]+/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .split(' ')
        .map((word) => {
            const lower = word.toLowerCase();
            if (['cbc', 'pcv', 'bun', 'wbc', 'alt', 'alp', 'elisa', 'pcr'].includes(lower)) return lower.toUpperCase();
            return `${word[0]?.toUpperCase() ?? ''}${word.slice(1).toLowerCase()}`;
        })
        .join(' ');
}
