export interface SoapDifferential {
    label: string;
    probability: number;
    urgency: string;
}

export interface SoapInferenceResult {
    inference_event_id: string;
    differentials: SoapDifferential[];
    confidence: number;
    recommended_tests: string[];
    cire?: {
        phi_hat?: number;
        cps?: number;
        safety_state?: string;
    } | null;
}

export interface SoapCaseInput {
    species?: string | null;
    breed?: string | null;
    age_years?: number | null;
    weight_kg?: number | null;
    sex?: string | null;
    presenting_complaint?: string | null;
    symptoms?: string[] | null;
    duration_text?: string | null;
    severity?: string | null;
    history?: string | null;
    vitals?: Record<string, unknown> | null;
    physical_exam?: Record<string, unknown> | null;
    labs?: Record<string, unknown> | null;
    voice_context?: Record<string, unknown> | null;
}

export function generateSOAP(inferenceResult: SoapInferenceResult, caseInput: SoapCaseInput): string {
    const phi = inferenceResult.cire?.phi_hat ?? inferenceResult.confidence;
    const voiceContext = asRecord(caseInput.voice_context);
    const rawTranscript = readText(voiceContext.raw_transcript);
    const extractionConfidence = readNumber(voiceContext.extraction_confidence);
    const sourceLine = rawTranscript
        ? `Voice-assisted intake${extractionConfidence == null ? '' : ` (${Math.round(extractionConfidence * 100)}% extraction confidence)`}`
        : 'Structured clinical intake';
    const patient = [
        caseInput.species ?? 'Unknown species',
        caseInput.breed,
        caseInput.age_years == null ? null : `${caseInput.age_years} years`,
        caseInput.weight_kg == null ? null : `${caseInput.weight_kg} kg`,
        caseInput.sex,
    ].filter(Boolean).join(' - ');
    const symptoms = caseInput.symptoms?.length
        ? caseInput.symptoms.join(', ')
        : caseInput.presenting_complaint ?? 'Not recorded';
    const topDifferential = inferenceResult.differentials[0];
    const tests = inferenceResult.recommended_tests.length > 0
        ? inferenceResult.recommended_tests.map((test) => `  [ ] ${formatSoapLabel(test)}`).join('\n')
        : '  [ ] Add confirmatory diagnostics based on clinician assessment.';
    const urgent = inferenceResult.differentials.some((entry) => entry.urgency === 'high' || entry.urgency === 'urgent' || entry.urgency === 'immediate');
    const reliabilityLabel = phiHatToLabel(phi);
    const clinicianAction = buildClinicianAction(phi, urgent, topDifferential?.label);
    const extractionNotes = readStringArray(voiceContext.extraction_notes);

    return `
SOAP NOTE - Generated by VetIOS
Date: ${new Date().toLocaleDateString()}
Case ID: ${inferenceResult.inference_event_id.slice(-8).toUpperCase()}
Intake source: ${sourceLine}

SUBJECTIVE
Patient: ${patient || 'Not recorded'}
Chief complaint: ${caseInput.presenting_complaint ?? symptoms}
Duration: ${caseInput.duration_text ?? 'Not specified'}
Severity: ${caseInput.severity ?? 'Not specified'}
Reported signs: ${symptoms}
History: ${caseInput.history ?? 'No additional history recorded.'}
${rawTranscript ? `Dictated note: ${rawTranscript}` : 'Dictated note: Not captured.'}
${extractionNotes.length ? `Extraction notes: ${extractionNotes.join('; ')}` : 'Extraction notes: No extraction warnings recorded.'}

OBJECTIVE
Vitals:
${formatRecord(caseInput.vitals, 'No vital signs recorded.')}

Physical exam:
${formatRecord(caseInput.physical_exam, 'No physical exam findings recorded.')}

Laboratory values:
${formatRecord(caseInput.labs, 'No laboratory values recorded.')}

ASSESSMENT
Differential diagnoses (AI-assisted, VetIOS):
${inferenceResult.differentials.map((entry, index) =>
        `  ${index + 1}. ${formatSoapLabel(entry.label)} - ${Math.round(entry.probability * 100)}% probability [${entry.urgency.toUpperCase()}]`
    ).join('\n') || '  No ranked differential was available.'}

Primary working assessment: ${topDifferential ? `${formatSoapLabel(topDifferential.label)} remains the leading VetIOS-ranked differential.` : 'No primary differential was available.'}
Reliability: ${reliabilityLabel} (phi ${phi.toFixed(2)})
Overall confidence: ${Math.round(inferenceResult.confidence * 100)}%
Clinical caution: This is a decision-support draft, not a confirmed diagnosis.

PLAN
Recommended diagnostics:
${tests}

Immediate clinician actions:
${clinicianAction.map((item) => `  [ ] ${item}`).join('\n')}

Treatment and monitoring:
  [ ] Stabilize patient as indicated by perfusion, hydration, pain, respiratory status, and clinician exam.
  [ ] Select therapy only after confirmatory evidence, contraindication review, and patient-specific dosing.
  [ ] Record medications, dose, route, frequency, duration, and owner instructions.

Follow-up:
  [ ] Recheck response within 24-48 hours or sooner if deterioration, dehydration, respiratory distress, collapse, persistent bleeding, or worsening pain occurs.
  [ ] Confirm final outcome in VetIOS once diagnosis is known.

Generated by VetIOS AI. Clinical judgment of the attending veterinarian applies.
Case reference: ${inferenceResult.inference_event_id.slice(-8).toUpperCase()}
`.trim();
}

function buildClinicianAction(phi: number, urgent: boolean, topLabel: string | undefined): string[] {
    const actions: string[] = [];
    if (urgent) {
        actions.push('Triage immediately; address shock, dehydration, respiratory distress, severe pain, or infectious isolation risk before routine workup.');
    }
    if (topLabel) {
        actions.push(`Confirm or rule out ${formatSoapLabel(topLabel)} with targeted diagnostics before closing the case.`);
    }
    if (phi < 0.75) {
        actions.push('Treat this as an uncertainty case; add history, exam findings, and confirmatory tests before irreversible treatment decisions.');
    } else {
        actions.push('Use the top differential as the initial working diagnosis while documenting confirmatory evidence.');
    }
    actions.push('Document owner consent, safety-net warnings, and follow-up plan.');
    return actions;
}

function formatRecord(record: Record<string, unknown> | null | undefined, emptyLabel: string): string {
    const entries = Object.entries(record ?? {})
        .filter(([, value]) => value !== null && value !== undefined && value !== '');

    if (entries.length === 0) return `  ${emptyLabel}`;

    return entries
        .map(([key, value]) => `  ${formatSoapLabel(key)}: ${String(value)}`)
        .join('\n');
}

function phiHatToLabel(phi: number): string {
    if (phi >= 0.75) return 'High reliability';
    if (phi >= 0.5) return 'Moderate reliability';
    return 'Low reliability - additional diagnostics recommended';
}

function formatSoapLabel(value: string): string {
    return value
        .replace(/[_-]+/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .split(' ')
        .map((word) => {
            const lower = word.toLowerCase();
            if (['cbc', 'pcv', 'bun', 'wbc', 'alt', 'alp', 'elisa', 'pcr'].includes(lower)) return lower.toUpperCase();
            return `${word[0]?.toUpperCase() ?? ''}${word.slice(1).toLowerCase()}`;
        })
        .join(' ');
}

function asRecord(value: unknown): Record<string, unknown> {
    return typeof value === 'object' && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function readText(value: unknown): string | null {
    return typeof value === 'string' && value.trim() ? value.trim() : null;
}

function readNumber(value: unknown): number | null {
    if (typeof value === 'number' && Number.isFinite(value)) return value;
    if (typeof value === 'string' && value.trim()) {
        const parsed = Number(value);
        return Number.isFinite(parsed) ? parsed : null;
    }
    return null;
}

function readStringArray(value: unknown): string[] {
    return Array.isArray(value)
        ? value.filter((entry): entry is string => typeof entry === 'string' && entry.trim().length > 0)
        : [];
}
