export const PUBLIC_SEO_PAGES = [
    {
        path: '/',
        title: 'VetIOS | AI-Native Veterinary Intelligence Infrastructure',
        description: 'Closed-loop veterinary AI infrastructure for inference, outcome learning, simulation, observability, and quantum-ready clinical intelligence.',
        priority: 1,
    },
    {
        path: '/about',
        title: 'About VetIOS',
        description: 'Learn what VetIOS is: AI-native veterinary intelligence infrastructure for inference, outcomes, graph intelligence, simulation, and AMR research.',
        priority: 0.92,
    },
    {
        path: '/veterinary-ai',
        title: 'Veterinary AI Platform',
        description: 'VetIOS is veterinary AI infrastructure for clinical inference, outcome learning, simulation, and auditable decision support.',
        priority: 0.95,
    },
    {
        path: '/veterinary-diagnostic-ai',
        title: 'Veterinary Diagnostic AI',
        description: 'AI-assisted veterinary differential diagnosis with structured inputs, graph priors, CIRE reliability signals, and outcome feedback.',
        priority: 0.94,
    },
    {
        path: '/quantum-veterinary-ai',
        title: 'Quantum Veterinary AI',
        description: 'Quantum-ready veterinary intelligence using Gaussian boson sampling for graph ranking, QIVS screening, and AMR RNA folding research.',
        priority: 0.9,
    },
    {
        path: '/platform',
        title: 'VetIOS Platform',
        description: 'Platform overview for veterinary inference, outcomes, simulation, graph intelligence, and quantum-ready infrastructure.',
        priority: 0.88,
    },
    {
        path: '/platform/cire-standard',
        title: 'VetIOS CIRE Open Standard',
        description: 'Public VetIOS clinical inference reliability standard for phi_hat, CPS, safety states, and outcome-linked audit lineage.',
        priority: 0.86,
    },
    {
        path: '/platform/developers',
        title: 'VetIOS Developer Platform',
        description: 'Public VetIOS developer API catalog, onboarding intake, quota model, and OpenAPI contract.',
        priority: 0.84,
    },
    {
        path: '/platform/network-learning',
        title: 'VetIOS Network Learning',
        description: 'Public VetIOS learning-loop evidence for dataset versions, benchmark reports, calibration, and federation readiness.',
        priority: 0.83,
    },
    {
        path: '/platform/edge-box',
        title: 'VetIOS Edge Box',
        description: 'Offline clinic node and cloud-edge synchronization plane for VetIOS veterinary intelligence infrastructure.',
        priority: 0.8,
    },
    {
        path: '/platform/passive-signals',
        title: 'VetIOS Passive Signals',
        description: 'Passive connector signal catalog for PIMS, lab, pharmacy, imaging, and workflow evidence ingestion.',
        priority: 0.8,
    },
    {
        path: '/platform/petpass',
        title: 'VetIOS PetPass',
        description: 'Consumer and clinic owner-network substrate for pet profiles, consent, timelines, and notifications.',
        priority: 0.78,
    },
    {
        path: '/platform/model-cards',
        title: 'VetIOS Public Model Cards',
        description: 'Read-only VetIOS model cards exposing registry state, governance gates, and promotion blockers.',
        priority: 0.77,
    },
    {
        path: '/platform/population-intelligence',
        title: 'VetIOS Population Intelligence',
        description: 'Aggregate disease surveillance and public-health safe advisory feed from VetIOS signal infrastructure.',
        priority: 0.77,
    },
    {
        path: '/docs',
        title: 'VetIOS Documentation',
        description: 'API reference and platform documentation for VetIOS veterinary AI infrastructure.',
        priority: 0.82,
    },
    {
        path: '/ask-vetios',
        title: 'Ask VetIOS',
        description: 'Public Ask VetIOS clinical intelligence console for veterinary questions, research-depth explanations, and differential reasoning.',
        priority: 0.81,
    },
    {
        path: '/demo',
        title: 'VetIOS Demo',
        description: 'Try a VetIOS veterinary diagnosis demo case without creating an account.',
        priority: 0.78,
    },
    {
        path: '/proofloop',
        title: 'VetIOS ProofLoop',
        description: 'See how a verified clinical outcome becomes an executable AI evaluation, regression test, and release gate.',
        priority: 0.86,
    },
    {
        path: '/support',
        title: 'VetIOS Support',
        description: 'Support and contact information for VetIOS platform operators and integration partners.',
        priority: 0.65,
    },
    {
        path: '/contact',
        title: 'Contact VetIOS',
        description: 'Contact VetIOS for platform access, veterinary AI partnerships, security reports, and integrations.',
        priority: 0.65,
    },
    {
        path: '/privacy',
        title: 'VetIOS Privacy Policy',
        description: 'Privacy policy for VetIOS veterinary clinical intelligence infrastructure.',
        priority: 0.45,
    },
    {
        path: '/terms',
        title: 'VetIOS Terms',
        description: 'Terms of service for VetIOS veterinary intelligence infrastructure.',
        priority: 0.45,
    },
] as const;

export const PUBLIC_SEO_PATHS = PUBLIC_SEO_PAGES.map((page) => page.path);
