import type { TreatmentProtocol } from '@/lib/inference/types';

const AHS = ['AHS 2024'];
const ESCCAP = ['ESCCAP 2023'];
const WSAVA = ['WSAVA Global Guidelines'];
const ACVIM = ['ACVIM 2019'];

function careProtocol(protocol: TreatmentProtocol): TreatmentProtocol {
    return protocol;
}

export const TREATMENT_PROTOCOLS: TreatmentProtocol[] = [
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['I', 'II', 'III', 'IV'],
        protocol_id: 'exercise_restriction',
        protocol_name: 'Strict exercise restriction',
        category: 'environmental_management',
        evidence_level: 'iv',
        guideline_source: AHS,
        recommendation_grade: 'A',
        treatment_phase: 'acute_stabilisation',
        priority: 'essential',
        expected_outcomes: 'Reduces fatal pulmonary thromboembolism risk during worm die-off.',
        treatment_failure_indicators: ['Exercise intolerance worsens with activity', 'Acute dyspnea after exertion'],
        alternative_if_fails: [],
        details: 'Strict cage rest from diagnosis through at least 8 weeks after adulticide therapy. Non-negotiable in all heartworm classes.',
    }),
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['I', 'II', 'III'],
        protocol_id: 'doxycycline_wolbachia',
        protocol_name: 'Doxycycline Wolbachia reduction',
        category: 'pharmacological_antibiotic',
        evidence_level: 'ib',
        guideline_source: AHS,
        recommendation_grade: 'A',
        treatment_phase: 'pre_treatment_preparation',
        priority: 'recommended',
        drug: {
            name: 'Doxycycline',
            drug_class: 'Tetracycline antibiotic',
            mechanism: 'Reduces Wolbachia endosymbionts and dampens pulmonary inflammatory burden before adulticide.',
            species: ['canine'],
            dosing: [{ amount_per_kg: 10, unit: 'mg', route: 'PO', frequency: 'q12h', duration: '28 days' }],
            route: ['PO'],
            contraindications: ['Documented doxycycline intolerance'],
            precautions: ['Give with food and water to reduce esophagitis risk'],
            drug_interactions: ['Antacids within 2 hours', 'Oral iron or calcium supplements'],
            adverse_effects: ['GI upset', 'Esophagitis'],
            monitoring_required: ['Clinical tolerance', 'Appetite'],
            availability: { africa_east: true, global: true },
            cost_tier: 'low',
        },
        treatment_duration: '28 days',
        follow_up_protocol: ['Complete before or immediately prior to adulticide'],
        expected_outcomes: 'Lowers worm-associated inflammatory response and reduces post-adulticide complications.',
        treatment_failure_indicators: ['Persistent intolerance', 'Progressive respiratory compromise'],
        alternative_if_fails: [],
    }),
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['I', 'II', 'III'],
        protocol_id: 'macrocyclic_lactone_microfilaricidal',
        protocol_name: 'Monthly macrocyclic lactone prevention and microfilarial control',
        category: 'pharmacological_antiparasitic',
        evidence_level: 'ib',
        guideline_source: AHS,
        recommendation_grade: 'A',
        treatment_phase: 'pre_treatment_preparation',
        priority: 'essential',
        drug: {
            name: 'Ivermectin or milbemycin oxime',
            drug_class: 'Macrocyclic lactone',
            mechanism: 'Clears microfilariae and prevents reinfection while definitive adulticide therapy is staged.',
            species: ['canine'],
            dosing: [
                { amount_per_kg: 6, amount_per_kg_high: 12, unit: 'mcg', route: 'PO', frequency: 'q30 days', duration: 'Monthly ongoing', notes: 'Ivermectin range' },
                { amount_per_kg: 0.5, unit: 'mg', route: 'PO', frequency: 'q30 days', duration: 'Monthly ongoing', notes: 'Milbemycin alternative for MDR1 concern' },
            ],
            route: ['PO'],
            contraindications: ['High-dose ivermectin in MDR1/ABCB1 mutation carriers'],
            precautions: ['Observe first dose in clinic if microfilaremic', 'Consider dexamethasone pretreatment in heavy microfilaremia'],
            drug_interactions: [],
            adverse_effects: ['Rare anaphylactoid reaction from rapid microfilarial death'],
            monitoring_required: ['Observation after first dose', 'Microfilaria burden'],
            availability: { africa_east: true, global: true },
            cost_tier: 'low',
        },
        expected_outcomes: 'Reduces larval burden and prevents reinfection during staged treatment.',
        treatment_failure_indicators: ['Anaphylactoid reaction', 'Persistent microfilaremia'],
        alternative_if_fails: [],
    }),
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['II', 'III'],
        protocol_id: 'prednisone_pulmonary_inflammation',
        protocol_name: 'Prednisone for pulmonary inflammation',
        category: 'pharmacological_immunosuppressive',
        evidence_level: 'iia',
        guideline_source: AHS,
        recommendation_grade: 'B',
        treatment_phase: 'adjunctive',
        priority: 'recommended',
        drug: {
            name: 'Prednisone',
            drug_class: 'Glucocorticoid',
            mechanism: 'Reduces pulmonary inflammation and post-adulticide inflammatory injury.',
            species: ['canine'],
            dosing: [{ amount_per_kg: 0.5, unit: 'mg', route: 'PO', frequency: 'q24h then taper q48h', duration: '2 weeks taper' }],
            route: ['PO'],
            contraindications: ['Uncontrolled diabetes mellitus', 'GI ulceration'],
            precautions: ['Use cautiously with active uncontrolled infection'],
            drug_interactions: ['NSAIDs'],
            adverse_effects: ['PU/PD', 'Panting', 'Polyphagia'],
            monitoring_required: ['Clinical response', 'Body weight'],
            availability: { africa_east: true, global: true },
            cost_tier: 'low',
        },
        expected_outcomes: 'Improves inflammatory comfort and reduces pulmonary reaction risk.',
        treatment_failure_indicators: ['Escalating respiratory signs', 'Steroid intolerance'],
        alternative_if_fails: [],
    }),
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['I', 'II', 'III'],
        protocol_id: 'melarsomine_split_dose',
        protocol_name: 'Melarsomine split-dose adulticide protocol',
        category: 'pharmacological_antiparasitic',
        evidence_level: 'ia',
        guideline_source: AHS,
        recommendation_grade: 'A',
        treatment_phase: 'definitive_treatment',
        priority: 'essential',
        drug: {
            name: 'Melarsomine dihydrochloride',
            drug_class: 'Adulticidal arsenical',
            mechanism: 'Kills adult Dirofilaria immitis in staged fashion to lower thromboembolic risk.',
            species: ['canine'],
            dosing: [{ amount_per_kg: 2.5, unit: 'mg', route: 'IM', frequency: 'Day 1, then Day 31 and Day 32', duration: 'Split-dose protocol' }],
            route: ['IM'],
            contraindications: ['Untreated caval syndrome', 'Unsafe injection route other than deep epaxial IM'],
            precautions: ['Hospitalize unstable Class III patients', 'Strict rest 6–8 weeks after injections'],
            drug_interactions: [],
            adverse_effects: ['Injection site pain', 'Pulmonary thromboembolism', 'Fever'],
            monitoring_required: ['Post-injection respiratory monitoring', '6-month antigen retest'],
            availability: { africa_east: false, europe: true, usa: true, global: false },
            cost_tier: 'high',
        },
        expected_outcomes: 'Achieves the highest adult worm kill rate with safest evidence-based schedule.',
        treatment_failure_indicators: ['Pulmonary thromboembolism', 'Persistent antigen positivity at 6 months'],
        alternative_if_fails: ['annual_monitoring_post_cure'],
        details: 'Preferred split-dose protocol for all non-caval heartworm classes.',
    }),
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['IV'],
        protocol_id: 'caval_syndrome_surgical_extraction',
        protocol_name: 'Transvenous worm extraction for caval syndrome',
        category: 'surgical',
        evidence_level: 'iii',
        guideline_source: AHS,
        recommendation_grade: 'B',
        treatment_phase: 'acute_stabilisation',
        priority: 'essential',
        surgery: {
            procedure_name: 'Transvenous heartworm extraction',
            technique: 'Jugular venotomy or catheter-guided transvenous extraction under imaging guidance.',
            specialist_required: true,
            anesthesia_considerations: ['High anesthetic risk', 'Maintain perfusion and oxygenation', 'Avoid negative inotropes'],
            perioperative_management: ['Oxygen support', 'ECG monitoring', 'ICU care 24–48 hours'],
            expected_outcomes: 'Improves hemodynamic stability enough to allow subsequent staged adulticide therapy.',
            complications: ['Arrhythmia', 'Worm fragmentation', 'Acute right heart failure', 'Hemorrhage'],
            recovery_protocol: 'Stabilise 2–4 weeks after extraction before melarsomine.',
        },
        expected_outcomes: 'Only evidence-supported rescue option for caval syndrome.',
        treatment_failure_indicators: ['Persistent shock', 'Recurrent collapse'],
        alternative_if_fails: [],
    }),
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['I', 'II', 'III', 'IV'],
        protocol_id: 'annual_monitoring_post_cure',
        protocol_name: 'Post-treatment monitoring and prevention',
        category: 'monitoring',
        evidence_level: 'iv',
        guideline_source: AHS,
        recommendation_grade: 'A',
        treatment_phase: 'long_term_management',
        priority: 'essential',
        expected_outcomes: 'Confirms cure, detects residual disease, and prevents reinfection.',
        treatment_failure_indicators: ['Persistent antigen positivity', 'Ongoing pulmonary lesions'],
        alternative_if_fails: ['melarsomine_split_dose'],
        details: 'Retest antigen and microfilariae at 6 months, repeat thoracic radiographs, then maintain monthly prevention and annual screening.',
    }),
    careProtocol({
        condition_id: 'dirofilariosis_canine',
        condition_name: 'Dirofilariosis (Heartworm disease)',
        severity_scope: ['I', 'II', 'III', 'IV'],
        protocol_id: 'owner_education_heartworm',
        protocol_name: 'Owner education and discharge counselling',
        category: 'owner_education',
        evidence_level: 'iv',
        guideline_source: AHS,
        recommendation_grade: 'A',
        treatment_phase: 'secondary_prevention',
        priority: 'essential',
        expected_outcomes: 'Improves compliance with exercise restriction, follow-up, and prevention.',
        treatment_failure_indicators: ['Missed prevention doses', 'Owner unable to maintain rest'],
        alternative_if_fails: [],
        details: 'Explain mosquito transmission, prevention adherence, pulmonary thromboembolism warning signs, and the monitoring schedule in writing.',
    }),
    careProtocol({ condition_id: 'pulmonary_hypertension', condition_name: 'Pulmonary hypertension', severity_scope: ['all'], protocol_id: 'pulmonary_hypertension_support', protocol_name: 'Pulmonary hypertension adjunctive support', category: 'pharmacological_cardiac', evidence_level: 'iii', guideline_source: WSAVA, recommendation_grade: 'B', treatment_phase: 'adjunctive', priority: 'recommended', drug: { name: 'Sildenafil', drug_class: 'PDE-5 inhibitor', mechanism: 'Reduces pulmonary vascular resistance.', species: ['canine'], dosing: [{ amount_per_kg: 1, amount_per_kg_high: 2, unit: 'mg', route: 'PO', frequency: 'q8-12h', duration: 'Ongoing as indicated' }], route: ['PO'], contraindications: ['Profound systemic hypotension'], precautions: ['Use with caution alongside aggressive vasodilators'], drug_interactions: ['Nitrates'], adverse_effects: ['GI upset', 'Hypotension'], monitoring_required: ['Respiratory effort', 'Echocardiographic reassessment'], availability: { africa_east: true, global: true }, cost_tier: 'moderate' }, expected_outcomes: 'Improves pulmonary pressure burden while underlying cause is treated.', treatment_failure_indicators: ['Progressive syncope', 'Worsening right-sided signs'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'right_sided_chf_secondary', condition_name: 'Right-sided CHF (secondary)', severity_scope: ['all'], protocol_id: 'right_sided_chf_support', protocol_name: 'Right-sided CHF supportive management', category: 'pharmacological_diuretic', evidence_level: 'iii', guideline_source: WSAVA, recommendation_grade: 'B', treatment_phase: 'adjunctive', priority: 'recommended', drug: { name: 'Furosemide', drug_class: 'Loop diuretic', mechanism: 'Reduces venous congestion and effusions.', species: ['canine'], dosing: [{ amount_per_kg: 1, amount_per_kg_high: 4, unit: 'mg', route: 'PO', frequency: 'q8-24h', duration: 'Titrate to effect' }], route: ['PO', 'IV'], contraindications: ['Severe dehydration'], precautions: ['Monitor renal perfusion and electrolytes'], drug_interactions: ['NSAIDs'], adverse_effects: ['Dehydration', 'Azotemia'], monitoring_required: ['Weight', 'Electrolytes', 'Renal values'], availability: { africa_east: true, global: true }, cost_tier: 'low' }, expected_outcomes: 'Controls congestion while primary cause is being corrected.', treatment_failure_indicators: ['Refractory ascites', 'Progressive azotemia'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'babesiosis_canine', condition_name: 'Babesiosis', severity_scope: ['all'], protocol_id: 'imidocarb_dipropionate', protocol_name: 'Imidocarb dipropionate therapy', category: 'pharmacological_antiparasitic', evidence_level: 'ib', guideline_source: ESCCAP, recommendation_grade: 'A', treatment_phase: 'definitive_treatment', priority: 'essential', drug: { name: 'Imidocarb dipropionate', drug_class: 'Antiprotozoal', mechanism: 'Interferes with protozoal nucleic acid metabolism.', species: ['canine'], dosing: [{ amount_per_kg: 6.6, unit: 'mg', route: 'IM', frequency: 'single dose, repeat in 14 days', duration: '2 doses' }], route: ['IM', 'SC'], contraindications: ['Severe cholinergic intolerance'], precautions: ['Premedicate atropine 0.05 mg/kg SC'], drug_interactions: [], adverse_effects: ['Pain', 'Salivation', 'Cholinergic effects'], monitoring_required: ['PCV/hematocrit', 'Platelet count'], availability: { africa_east: true, global: true }, cost_tier: 'moderate' }, expected_outcomes: 'Clears large Babesia species with repeat dosing.', treatment_failure_indicators: ['Persistent parasitemia', 'Recurrent hemolysis'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'ehrlichiosis_canine', condition_name: 'Ehrlichiosis', severity_scope: ['all'], protocol_id: 'doxycycline_ehrlichia', protocol_name: 'Doxycycline anti-rickettsial therapy', category: 'pharmacological_antibiotic', evidence_level: 'ib', guideline_source: ESCCAP, recommendation_grade: 'A', treatment_phase: 'definitive_treatment', priority: 'essential', drug: { name: 'Doxycycline', drug_class: 'Tetracycline antibiotic', mechanism: 'Clears intracellular Ehrlichia infection.', species: ['canine'], dosing: [{ amount_per_kg: 10, unit: 'mg', route: 'PO', frequency: 'q24h or divided q12h', duration: '28 days' }], route: ['PO'], contraindications: ['Documented tetracycline intolerance'], precautions: ['Give with food'], drug_interactions: ['Antacids'], adverse_effects: ['GI upset'], monitoring_required: ['CBC recheck in 2-4 weeks'], availability: { africa_east: true, global: true }, cost_tier: 'low' }, expected_outcomes: 'Primary evidence-based therapy for acute and chronic ehrlichiosis.', treatment_failure_indicators: ['Persistent thrombocytopenia', 'Progressive pancytopenia'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'leishmaniosis_canine', condition_name: 'Leishmaniosis', severity_scope: ['all'], protocol_id: 'allopurinol_meglumine', protocol_name: 'Meglumine antimoniate plus allopurinol', category: 'pharmacological_antiparasitic', evidence_level: 'iia', guideline_source: ESCCAP, recommendation_grade: 'A', treatment_phase: 'definitive_treatment', priority: 'recommended', drug: { name: 'Meglumine antimoniate with allopurinol', drug_class: 'Antileishmanial combination', mechanism: 'Direct antiprotozoal effect with long-term parasite suppression.', species: ['canine'], dosing: [{ amount_per_kg: 75, amount_per_kg_high: 100, unit: 'mg', route: 'SC', frequency: 'q24h', duration: '28 days', notes: 'Meglumine antimoniate' }, { amount_per_kg: 10, unit: 'mg', route: 'PO', frequency: 'q12h', duration: 'Long term', notes: 'Allopurinol maintenance' }], route: ['SC', 'PO'], contraindications: ['Severe xanthinuria risk without monitoring'], precautions: ['Renal monitoring mandatory'], drug_interactions: [], adverse_effects: ['Injection discomfort', 'GI upset', 'Xanthine uroliths'], monitoring_required: ['UPC ratio', 'Creatinine', 'Globulins'], availability: { europe: true, africa_east: false, global: false }, cost_tier: 'high' }, expected_outcomes: 'Best-supported control protocol where meglumine is available.', treatment_failure_indicators: ['Progressive proteinuria', 'Clinical relapse'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'leptospirosis', condition_name: 'Leptospirosis', severity_scope: ['all'], protocol_id: 'penicillin_doxycycline', protocol_name: 'Acute leptospirosis antimicrobial sequence', category: 'pharmacological_antibiotic', evidence_level: 'ib', guideline_source: WSAVA, recommendation_grade: 'A', treatment_phase: 'definitive_treatment', priority: 'essential', drug: { name: 'Penicillin G then doxycycline', drug_class: 'Sequential antibiotic therapy', mechanism: 'Clears leptospiremia then eliminates carrier state.', species: ['canine'], dosing: [{ amount_per_kg: 25000, amount_per_kg_high: 40000, unit: 'IU', route: 'IV', frequency: 'q12h', duration: '14 days', notes: 'Penicillin G' }, { amount_per_kg: 5, unit: 'mg', route: 'PO', frequency: 'q12h', duration: '14 days', notes: 'Doxycycline follow-on' }], route: ['IV', 'PO'], contraindications: [], precautions: ['Zoonotic precautions essential'], drug_interactions: [], adverse_effects: ['GI upset'], monitoring_required: ['Urine output', 'Renal and hepatic values'], availability: { africa_east: true, global: true }, cost_tier: 'moderate' }, expected_outcomes: 'Preferred antimicrobial sequence for leptospirosis.', treatment_failure_indicators: ['Persistent azotemia', 'Oliguria'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'parvoviral_enteritis', condition_name: 'Parvoviral enteritis', severity_scope: ['all'], protocol_id: 'parvo_supportive_bundle', protocol_name: 'Parvoviral supportive care bundle', category: 'pharmacological_supportive', evidence_level: 'iia', guideline_source: WSAVA, recommendation_grade: 'A', treatment_phase: 'acute_stabilisation', priority: 'essential', details: 'Aggressive isotonic IV fluids, maropitant, IV antibiotics for bacterial translocation risk, early enteral feeding once vomiting is controlled, transfusion support if protein depleted.', expected_outcomes: 'Improves survival when early intensive supportive care is delivered.', treatment_failure_indicators: ['Refractory shock', 'Persistent severe leukopenia'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'mitral_valve_disease_canine', condition_name: 'Mitral valve disease', severity_scope: ['B2', 'C', 'D'], protocol_id: 'mvd_stage_based', protocol_name: 'ACVIM stage-based mitral valve management', category: 'pharmacological_cardiac', evidence_level: 'ib', guideline_source: ACVIM, recommendation_grade: 'A', treatment_phase: 'long_term_management', priority: 'essential', details: 'B2: pimobendan only. C: pimobendan + furosemide + ACE inhibitor. D: add spironolactone and consider torsemide or digoxin.', expected_outcomes: 'Standard evidence-based chronic valve disease management.', treatment_failure_indicators: ['Refractory CHF', 'Syncope'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'tracheal_collapse', condition_name: 'Tracheal Collapse', severity_scope: ['all'], protocol_id: 'tracheal_collapse_medical', protocol_name: 'Medical airway stabilisation and weight control', category: 'pharmacological_bronchodilator', evidence_level: 'iii', guideline_source: WSAVA, recommendation_grade: 'B', treatment_phase: 'long_term_management', priority: 'recommended', details: 'Bronchodilators, antitussives, short anti-inflammatory course if inflamed, harness instead of collar, aggressive weight control, and consider interventional stenting for advanced disease.', expected_outcomes: 'Reduces cough frequency and dynamic airway distress in confirmed cases.', treatment_failure_indicators: ['Persistent respiratory distress', 'Cyanotic episodes'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'hyperadrenocorticism_canine', condition_name: 'Hyperadrenocorticism', severity_scope: ['all'], protocol_id: 'trilostane_protocol', protocol_name: 'Trilostane first-line medical management', category: 'pharmacological_hormonal', evidence_level: 'ib', guideline_source: WSAVA, recommendation_grade: 'A', treatment_phase: 'definitive_treatment', priority: 'essential', details: 'Trilostane 1-2 mg/kg PO q24h with food; ACTH stimulation monitoring every 3-6 months. Mitotane or adrenalectomy reserved for selected cases.', expected_outcomes: 'Preferred reversible treatment for pituitary-dependent disease.', treatment_failure_indicators: ['Persistent PU/PD', 'Post-treatment hypocortisolemia'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'hypothyroidism_canine', condition_name: 'Hypothyroidism', severity_scope: ['all'], protocol_id: 'levothyroxine_replacement', protocol_name: 'Levothyroxine replacement therapy', category: 'pharmacological_hormonal', evidence_level: 'ib', guideline_source: WSAVA, recommendation_grade: 'A', treatment_phase: 'definitive_treatment', priority: 'essential', drug: { name: 'Levothyroxine', drug_class: 'Thyroid hormone replacement', mechanism: 'Replaces deficient thyroxine.', species: ['canine'], dosing: [{ amount_per_kg: 0.02, unit: 'mg', route: 'PO', frequency: 'q24h or divided q12h', duration: 'Lifelong' }], route: ['PO'], contraindications: [], precautions: ['Recheck total T4 4-6 hours after dosing at 4-8 weeks'], drug_interactions: [], adverse_effects: ['Iatrogenic hyperthyroidism if overdosed'], monitoring_required: ['T4 monitoring', 'Clinical response'], availability: { africa_east: true, global: true }, cost_tier: 'low' }, expected_outcomes: 'Standard lifelong hormone replacement.', treatment_failure_indicators: ['Persistent lethargy with adequate T4'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'diabetes_mellitus_canine', condition_name: 'Diabetes mellitus', severity_scope: ['all'], protocol_id: 'insulin_nph_protocol', protocol_name: 'Canine insulin protocol with diet control', category: 'pharmacological_hormonal', evidence_level: 'ib', guideline_source: WSAVA, recommendation_grade: 'A', treatment_phase: 'definitive_treatment', priority: 'essential', details: 'Initiate NPH insulin around 0.25 IU/kg SC q12h, consistent measured feeding schedule, and glucose curve or fructosamine monitoring. Treat concurrent disease and train owner in hypoglycemia recognition.', expected_outcomes: 'Evidence-based first-line diabetic management in dogs.', treatment_failure_indicators: ['Persistent hyperglycemia', 'Hypoglycemic events'], alternative_if_fails: [] }),
    careProtocol({ condition_id: 'immune_mediated_hemolytic_anemia', condition_name: 'Immune-mediated haemolytic anaemia', severity_scope: ['all'], protocol_id: 'imha_immunosuppression_bundle', protocol_name: 'IMHA immunosuppression and thromboprophylaxis bundle', category: 'pharmacological_immunosuppressive', evidence_level: 'iii', guideline_source: WSAVA, recommendation_grade: 'A', treatment_phase: 'acute_stabilisation', priority: 'essential', details: 'Prednisone 1-2 mg/kg/day, consider cyclosporine or mycophenolate, transfuse if decompensated, and provide thromboprophylaxis with heparin or clopidogrel.', expected_outcomes: 'Core IMHA rescue strategy used internationally.', treatment_failure_indicators: ['Refractory hemolysis', 'Thromboembolism'], alternative_if_fails: [] }),
];

export function getTreatmentProtocolsForCondition(conditionId: string): TreatmentProtocol[] {
    return TREATMENT_PROTOCOLS.filter((protocol) => protocol.condition_id === conditionId);
}
