-- ─── Tier 2: One Health Cross-Species Surveillance ────────────────────────────
-- Connects to: ai_inference_events, causal_observations, population_signals
--
-- Two tables:
--   one_health_signals      — cross-species disease signal with zoonotic risk
--   zoonotic_bridge_alerts  — alerts when animal cases indicate human exposure risk

-- ── 1. One Health Signals ─────────────────────────────────────────────────────
-- One row per confirmed diagnosis event enriched with zoonotic context.
-- Written by ZoonoticBridgeEngine on every confirmed outcome.
CREATE TABLE IF NOT EXISTS one_health_signals (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID NOT NULL,
  inference_event_id    UUID REFERENCES ai_inference_events(id) ON DELETE SET NULL,

  -- Clinical context
  species               TEXT NOT NULL,
  breed                 TEXT,
  region                TEXT,
  confirmed_diagnosis   TEXT NOT NULL,
  pathogen              TEXT,                  -- VKG pathogen node label

  -- Zoonotic classification
  is_zoonotic           BOOLEAN NOT NULL DEFAULT FALSE,
  zoonotic_risk_level   TEXT,                  -- 'high'|'moderate'|'low'|'none'
  human_exposure_risk   FLOAT,                 -- 0-1
  zoonotic_pathway      TEXT,                  -- 'direct_contact'|'vector'|'foodborne'|'airborne'

  -- Signal metadata
  iso_week              TEXT NOT NULL,         -- e.g. '2026-W18'
  signal_weight         FLOAT NOT NULL DEFAULT 1.0,

  created_at            TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. Zoonotic Bridge Alerts ─────────────────────────────────────────────────
-- Aggregated alerts when animal case clusters indicate human exposure risk.
-- Threshold-based: generated by OutbreakSurveillanceService.
CREATE TABLE IF NOT EXISTS zoonotic_bridge_alerts (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             UUID,                  -- null = network-wide alert

  -- Alert context
  pathogen              TEXT NOT NULL,
  animal_species        TEXT[],                -- which species are affected
  region                TEXT,
  iso_week              TEXT NOT NULL,

  -- Alert classification
  alert_type            TEXT NOT NULL,         -- 'zoonotic_cluster'|'who_threshold'|'novel_host'|'geographic_spread'
  severity              TEXT NOT NULL,         -- 'watch'|'warning'|'alert'|'emergency'
  zoonotic_risk_level   TEXT NOT NULL,         -- 'high'|'moderate'|'low'

  -- Evidence
  animal_case_count     INTEGER NOT NULL DEFAULT 0,
  affected_clinic_count INTEGER NOT NULL DEFAULT 0,
  supporting_signal_ids UUID[],

  -- Content
  title                 TEXT NOT NULL,
  description           TEXT NOT NULL,
  recommended_actions   TEXT[],
  who_notification_warranted BOOLEAN DEFAULT FALSE,

  -- Lifecycle
  first_detected_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at           TIMESTAMPTZ,
  created_at            TIMESTAMPTZ DEFAULT NOW()
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS one_health_signals_region_idx
  ON one_health_signals(region, iso_week);
CREATE INDEX IF NOT EXISTS one_health_signals_pathogen_idx
  ON one_health_signals(pathogen, is_zoonotic);
CREATE INDEX IF NOT EXISTS one_health_signals_diagnosis_idx
  ON one_health_signals(confirmed_diagnosis, species);
CREATE INDEX IF NOT EXISTS one_health_signals_week_idx
  ON one_health_signals(iso_week, zoonotic_risk_level);
CREATE INDEX IF NOT EXISTS zoonotic_alerts_pathogen_region_idx
  ON zoonotic_bridge_alerts(pathogen, region, iso_week);
CREATE INDEX IF NOT EXISTS zoonotic_alerts_severity_idx
  ON zoonotic_bridge_alerts(severity, zoonotic_risk_level);

-- ── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE one_health_signals      ENABLE ROW LEVEL SECURITY;
ALTER TABLE zoonotic_bridge_alerts  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_one_health_signals"
  ON one_health_signals FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_zoonotic_bridge_alerts"
  ON zoonotic_bridge_alerts FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMENT ON TABLE one_health_signals IS
  'Tier 2 — cross-species disease signals with zoonotic risk classification';
COMMENT ON TABLE zoonotic_bridge_alerts IS
  'Tier 2 — alerts when animal clusters indicate human exposure risk';
