import { getTreatmentProtocolsForCondition } from '../treatment/treatment-registry';
import type { Species, VeterinaryCondition } from './types';

const AVIAN: Species[] = ['avian'];
const REPTILE: Species[] = ['reptile'];
const EXOTIC: Species[] = ['exotic'];
const AVIAN_REPTILE_EXOTIC_REFS = [
    'WOAH animal health disease references',
    'Merck Veterinary Manual avian and reptile medicine references',
    'Peer-reviewed exotic animal internal medicine literature',
];

function condition(input: Omit<VeterinaryCondition, 'treatments'>): VeterinaryCondition {
    return {
        ...input,
        treatments: getTreatmentProtocolsForCondition(input.id),
    };
}

export const AVIAN_REPTILE_EXOTIC_CONDITIONS: VeterinaryCondition[] = [
    condition({
        id: 'avian_chlamydiosis',
        canonical_name: 'Avian Chlamydiosis',
        aliases: ['Psittacosis', 'Chlamydia psittaci infection'],
        species_affected: AVIAN,
        etiological_class: 'bacterial',
        causative_agent: 'Chlamydia psittaci',
        vector: [],
        transmission_route: ['Aerosolized secretions', 'Fecal dust', 'Direct contact'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'pcr.chlamydia_psittaci_pcr', result: 'positive', probability_if_positive: 0.95, evidence_label: 'Positive Chlamydia psittaci PCR', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cytology.heterophils', result: 'elevated', boost: 0.08, evidence_label: 'Heterophilic inflammation' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['respiratory_signs', 'ocular_discharge'],
        common_signs: ['lethargy', 'anorexia', 'diarrhea', 'nasal_discharge'],
        rare_signs: ['neurologic_signs'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: AVIAN_REPTILE_EXOTIC_REFS,
    }),
    condition({
        id: 'avian_aspergillosis',
        canonical_name: 'Avian Aspergillosis',
        aliases: ['Aspergillus infection in birds'],
        species_affected: AVIAN,
        etiological_class: 'fungal',
        causative_agent: 'Aspergillus spp.',
        vector: [],
        transmission_route: ['Environmental spore inhalation'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'pcr.aspergillus_pcr', result: 'positive', probability_if_positive: 0.88, evidence_label: 'Positive Aspergillus PCR', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cytology.heterophils', result: 'elevated', boost: 0.1, evidence_label: 'Heterophilic inflammation' },
            { test: 'cbc.heterophil_lymphocyte_ratio', boost: 0.08, evidence_label: 'High H:L ratio' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['respiratory_distress', 'dyspnea'],
        common_signs: ['lethargy', 'weight_loss', 'exercise_intolerance'],
        rare_signs: ['neurologic_signs'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: AVIAN_REPTILE_EXOTIC_REFS,
    }),
    condition({
        id: 'avian_influenza_alert',
        canonical_name: 'Avian Influenza Alert',
        aliases: ['Avian influenza', 'AI alert'],
        species_affected: AVIAN,
        etiological_class: 'viral',
        causative_agent: 'Avian influenza virus',
        vector: [],
        transmission_route: ['Direct contact', 'Fomite', 'Wild bird exposure'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01 },
        pathognomonic_tests: [
            { test: 'pcr.avian_influenza_pcr', result: 'positive', probability_if_positive: 0.98, evidence_label: 'Positive avian influenza PCR', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['sudden_death', 'respiratory_signs'],
        common_signs: ['neurologic_signs', 'diarrhea', 'cyanosis', 'lethargy'],
        rare_signs: ['edema'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: AVIAN_REPTILE_EXOTIC_REFS,
    }),
    condition({
        id: 'reptile_metabolic_bone_disease',
        canonical_name: 'Reptile Metabolic Bone Disease',
        aliases: ['Nutritional secondary hyperparathyroidism', 'MBD'],
        species_affected: REPTILE,
        etiological_class: 'nutritional',
        causative_agent: 'Calcium, vitamin D3, UVB, or phosphorus imbalance',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.06 },
        pathognomonic_tests: [
            { test: 'biochemistry.calcium', result: 'low', probability_if_positive: 0.82, evidence_label: 'Low calcium', required_for_confirmation: true },
            { test: 'biochemistry.calcium', result: 'hypocalcemia', probability_if_positive: 0.86, evidence_label: 'Hypocalcaemia', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'biochemistry.phosphorus', result: 'elevated', boost: 0.12, evidence_label: 'Elevated phosphorus' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['weakness', 'lameness'],
        common_signs: ['anorexia', 'fracture', 'paresis', 'tremors'],
        rare_signs: ['seizures'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: AVIAN_REPTILE_EXOTIC_REFS,
    }),
    condition({
        id: 'reptile_infectious_stomatitis_septicemia',
        canonical_name: 'Reptile Infectious Stomatitis / Septicaemia Risk',
        aliases: ['Mouth rot', 'Reptile septicemia risk'],
        species_affected: REPTILE,
        etiological_class: 'bacterial',
        causative_agent: 'Opportunistic bacterial infection with systemic spread risk',
        vector: [],
        transmission_route: ['Husbandry-associated opportunistic infection', 'Trauma-associated infection'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.04 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'cytology.toxic_changes', result: 'present', boost: 0.16, evidence_label: 'Toxic inflammatory changes' },
            { test: 'microbiology.growth', result: 'heavy', boost: 0.16, evidence_label: 'Heavy bacterial culture growth' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['oral_ulceration', 'anorexia'],
        common_signs: ['lethargy', 'swelling', 'discharge'],
        rare_signs: ['sepsis'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: AVIAN_REPTILE_EXOTIC_REFS,
    }),
    condition({
        id: 'exotic_small_mammal_gi_stasis',
        canonical_name: 'Exotic Small Mammal Gastrointestinal Stasis',
        aliases: ['Rabbit GI stasis', 'Ileus in exotic small mammals'],
        species_affected: EXOTIC,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Multifactorial hypomotility, pain, diet, dental disease, or systemic illness',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.05 },
        pathognomonic_tests: [],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['anorexia', 'reduced_feces'],
        common_signs: ['lethargy', 'abdominal_pain', 'dehydration'],
        rare_signs: ['shock'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: AVIAN_REPTILE_EXOTIC_REFS,
    }),
];
