import { getTreatmentProtocolsForCondition } from '../treatment/treatment-registry';
import type { Species, VeterinaryCondition } from './types';

const CORE_REFS = ['WSAVA Global Guidelines', 'ESCCAP 2023', 'Peer-reviewed veterinary internal medicine literature'];
const AHS_REFS = ['AHS 2024', 'ESCCAP 2023', 'Peer-reviewed cardiopulmonary parasitology literature'];
const FELINE_URI_REFS = ['AAFP feline upper respiratory guidance', 'ISFM feline medicine guidance', 'Peer-reviewed feline infectious respiratory literature'];

function buildCondition(condition: Omit<VeterinaryCondition, 'treatments'>): VeterinaryCondition {
    return {
        ...condition,
        treatments: getTreatmentProtocolsForCondition(condition.id),
    };
}

const CANINE: Species[] = ['canine'];
const FELINE: Species[] = ['feline'];
const BOVINE: Species[] = ['bovine'];

export const VETERINARY_CONDITIONS: VeterinaryCondition[] = [
    buildCondition({
        id: 'dirofilariosis_canine',
        canonical_name: 'Dirofilariosis (Heartworm disease)',
        aliases: ['Heartworm disease', 'Dirofilaria immitis infection'],
        species_affected: CANINE,
        etiological_class: 'parasitic_helminth',
        causative_agent: 'Dirofilaria immitis',
        vector: ['Culex mosquito', 'Aedes mosquito', 'Anopheles mosquito'],
        transmission_route: ['Mosquito-borne'],
        geographic_distribution: ['east_africa', 'sub_saharan_africa', 'mediterranean', 'usa_southeast', 'usa_nationwide'],
        regional_prevalence: { nairobi_ke: 0.08, mombasa_ke: 0.18, east_africa: 0.10, sub_saharan_africa: 0.12, mediterranean: 0.08, usa_southeast: 0.22, usa_nationwide: 0.12, western_europe: 0.02 },
        pathognomonic_tests: [
            { test: 'serology.dirofilaria_immitis_antigen', result: 'positive', probability_if_positive: 0.97, probability_if_negative: 0.05, evidence_label: 'Positive Dirofilaria immitis antigen test', required_for_confirmation: true },
            { test: 'echocardiography.worms_visualised', result: 'present', probability_if_positive: 0.99, evidence_label: 'Echocardiographic worm visualisation', required_for_confirmation: true },
            { test: 'parasitology.knott_test', result: 'positive_microfilariae', probability_if_positive: 0.85, probability_if_negative: 0.1, evidence_label: 'Positive Knott test' },
        ],
        supporting_tests: [
            { test: 'thoracic_radiograph.pulmonary_artery_enlargement', result: 'present', boost: 0.40, evidence_label: 'Pulmonary artery enlargement' },
            { test: 'thoracic_radiograph.cardiomegaly', result: 'right_sided', boost: 0.30, evidence_label: 'Right-sided cardiomegaly' },
            { test: 'cbc.eosinophilia', boost: 0.15, evidence_label: 'Eosinophilia' },
        ],
        exclusion_criteria: [
            { field: 'serology.dirofilaria_immitis_antigen', expected_value: 'negative', explanation: 'Negative antigen markedly reduces heartworm probability.', penalty: 0.8 },
        ],
        cardinal_signs: ['chronic_cough', 'exercise_intolerance'],
        common_signs: ['dyspnea', 'weight_loss', 'lethargy', 'syncope', 'hemoptysis', 'ascites'],
        rare_signs: ['caval_syndrome', 'collapse'],
        signs_that_exclude: [],
        imaging_patterns: [
            { finding: 'thoracic_radiograph.pulmonary_artery_enlargement', result: 'present', boost: 0.40, evidence_label: 'Pulmonary artery enlargement on radiograph' },
            { finding: 'thoracic_radiograph.cardiomegaly', result: 'right_sided', boost: 0.30, evidence_label: 'Right heart enlargement pattern' },
        ],
        haematological_patterns: [
            { finding: 'cbc.eosinophilia', result: 'present', boost: 0.15, evidence_label: 'Eosinophilia' },
            { finding: 'cbc.basophilia', result: 'present', boost: 0.10, evidence_label: 'Basophilia' },
            { finding: 'cbc.microfilaremia', result: 'present', boost: 0.35, evidence_label: 'Microfilaremia' },
        ],
        severity_classification: [
            { class: 'I', label: 'Mild — asymptomatic or mild signs' },
            { class: 'II', label: 'Moderate — cough and exercise intolerance' },
            { class: 'III', label: 'Severe — dyspnea, cachexia, syncope' },
            { class: 'IV', label: 'Caval syndrome — sudden cardiovascular collapse' },
        ],
        references: AHS_REFS,
    }),
    buildCondition({ id: 'tracheal_collapse', canonical_name: 'Tracheal Collapse', aliases: ['Tracheal collapse syndrome'], species_affected: CANINE, etiological_class: 'respiratory_structural', causative_agent: 'Dynamic airway collapse', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [{ test: 'thoracic_radiograph.tracheal_collapse_seen', result: 'present', probability_if_positive: 0.93 }, { test: 'fluoroscopy.tracheal_collapse', result: 'present', probability_if_positive: 0.97 }], supporting_tests: [], exclusion_criteria: [{ field: 'breed.large_breed', explanation: 'Large breed status dramatically lowers prior for tracheal collapse.', penalty: 0.4 }, { field: 'thoracic_radiograph.pulmonary_artery_enlargement', explanation: 'Pulmonary artery enlargement argues against tracheal collapse as the primary diagnosis.', penalty: 0.45 }, { field: 'echocardiography.right_heart_enlargement', explanation: 'Right-heart enlargement argues against tracheal collapse as the primary diagnosis.', penalty: 0.4 }], cardinal_signs: ['honking_cough'], common_signs: ['exercise_intolerance', 'respiratory_distress'], rare_signs: [], signs_that_exclude: ['large_breed'], imaging_patterns: [{ finding: 'thoracic_radiograph.tracheal_collapse_seen', result: 'present', boost: 0.45, evidence_label: 'Tracheal collapse visualised' }], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'chronic_bronchitis_canine', canonical_name: 'Primary Bronchitis', aliases: ['Chronic bronchitis'], species_affected: CANINE, etiological_class: 'respiratory_structural', causative_agent: 'Chronic inflammatory airway disease', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.05 }, pathognomonic_tests: [{ test: 'bronchoscopy.bal_neutrophilia', result: 'present', probability_if_positive: 0.85 }], supporting_tests: [], exclusion_criteria: [{ field: 'serology.dirofilaria_immitis_antigen', explanation: 'Positive heartworm antigen excludes primary bronchitis as the main explanation.', exclude: true }, { field: 'thoracic_radiograph.pulmonary_artery_enlargement', explanation: 'Pulmonary artery enlargement makes bronchitis insufficient as the primary diagnosis.', penalty: 0.25 }], cardinal_signs: ['chronic_cough'], common_signs: ['productive_cough'], rare_signs: [], signs_that_exclude: ['systemic_signs'], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'pulmonary_hypertension', canonical_name: 'Pulmonary Hypertension', aliases: ['Pulmonary hypertension (secondary to dirofilariosis)'], species_affected: CANINE, etiological_class: 'respiratory_structural', causative_agent: 'Pulmonary vascular hypertension', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [{ test: 'echocardiography.pulmonary_hypertension', result: 'present', probability_if_positive: 0.9 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['exercise_intolerance'], common_signs: ['dyspnea', 'syncope'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [{ finding: 'thoracic_radiograph.pulmonary_artery_enlargement', result: 'present', boost: 0.2, evidence_label: 'Pulmonary vascular enlargement' }], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'right_sided_chf_secondary', canonical_name: 'Right-sided CHF (secondary)', aliases: ['Right-sided congestive heart failure'], species_affected: CANINE, etiological_class: 'cardiovascular_structural', causative_agent: 'Secondary right-heart failure', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [], supporting_tests: [], exclusion_criteria: [{ field: 'primary_cause', explanation: 'Right-sided CHF is incomplete without identifying the primary cause.', penalty: 0.2 }], cardinal_signs: ['ascites'], common_signs: ['jugular_distension', 'hepatomegaly', 'pleural_effusion'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [{ finding: 'echocardiography.right_heart_enlargement', result: 'present', boost: 0.16, evidence_label: 'Right heart enlargement' }], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'laryngeal_paralysis', canonical_name: 'Laryngeal Paralysis', aliases: [], species_affected: CANINE, etiological_class: 'respiratory_structural', causative_agent: 'Arytenoid dysfunction', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [{ test: 'laryngoscopy.arytenoid_immobility', result: 'present', probability_if_positive: 0.95 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['inspiratory_stridor'], common_signs: ['voice_change', 'exercise_intolerance', 'dyspnea'], rare_signs: ['aspiration_pneumonia'], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'diabetes_mellitus_canine', canonical_name: 'Diabetes Mellitus', aliases: ['Diabetes mellitus canine'], species_affected: CANINE, etiological_class: 'metabolic_endocrine', causative_agent: 'Insulin deficiency', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [{ test: 'biochemistry.glucose', result: 'hyperglycemia', probability_if_positive: 0.88, evidence_label: 'Persistent hyperglycemia', required_for_confirmation: true }, { test: 'urinalysis.glucose_in_urine', result: 'present', probability_if_positive: 0.88, evidence_label: 'Glucosuria', required_for_confirmation: true }], supporting_tests: [], exclusion_criteria: [{ field: 'urinalysis.glucose_in_urine', explanation: 'Diabetes cannot be primary without glucosuria.', exclude: true }, { field: 'biochemistry.glucose', explanation: 'Diabetes cannot be primary without hyperglycemia.', exclude: true }], cardinal_signs: ['polyuria', 'polydipsia'], common_signs: ['polyphagia', 'weight_loss', 'cataracts'], rare_signs: [], signs_that_exclude: ['weight_gain'], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'hypothyroidism_canine', canonical_name: 'Hypothyroidism', aliases: ['Canine hypothyroidism'], species_affected: CANINE, etiological_class: 'metabolic_endocrine', causative_agent: 'Thyroid hormone deficiency', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.04 }, pathognomonic_tests: [{ test: 'serology.t4_total', result: 'low', probability_if_positive: 0.82 }, { test: 'serology.total_t4', result: 'low', probability_if_positive: 0.88, evidence_label: 'Low total T4', required_for_confirmation: true }, { test: 'serology.free_t4', result: 'low', probability_if_positive: 0.88 }], supporting_tests: [], exclusion_criteria: [{ field: 'presenting_signs', expected_value: 'weight_loss', explanation: 'Weight loss weakens hypothyroidism because classic disease causes weight gain.', penalty: 0.5 }], cardinal_signs: ['lethargy'], common_signs: ['weight_gain', 'cold_intolerance', 'skin_changes', 'bradycardia'], rare_signs: ['facial_myxedema'], signs_that_exclude: ['weight_loss'], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'babesiosis_canine', canonical_name: 'Babesiosis', aliases: ['Babesia rossi infection', 'Babesia gibsoni infection'], species_affected: CANINE, etiological_class: 'parasitic_protozoan', causative_agent: 'Babesia rossi / gibsoni / canis / vogeli', vector: ['Haemaphysalis tick', 'Rhipicephalus tick'], transmission_route: ['Tick-borne'], geographic_distribution: ['east_africa', 'south_africa', 'southern_europe'], regional_prevalence: { east_africa: 0.14, nairobi_ke: 0.12, south_africa: 0.25, southern_europe: 0.08 }, pathognomonic_tests: [{ test: 'parasitology.buffy_coat_smear', result: 'babesia', probability_if_positive: 0.95, evidence_label: 'Babesia seen on buffy coat smear', required_for_confirmation: true }, { test: 'pcr.babesia_pcr', result: 'positive', probability_if_positive: 0.96, evidence_label: 'Positive Babesia PCR', required_for_confirmation: true }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['lethargy'], common_signs: ['pale_mucous_membranes', 'fever', 'weakness'], rare_signs: ['icterus'], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.thrombocytopenia', result: 'severe', boost: 0.18, evidence_label: 'Severe thrombocytopenia' }, { finding: 'cbc.anemia_type', result: 'regenerative', boost: 0.15, evidence_label: 'Regenerative anemia' }], references: CORE_REFS }),
    buildCondition({ id: 'ehrlichiosis_canine', canonical_name: 'Ehrlichiosis', aliases: ['Ehrlichia canis infection'], species_affected: CANINE, etiological_class: 'parasitic_protozoan', causative_agent: 'Ehrlichia canis', vector: ['Rhipicephalus sanguineus'], transmission_route: ['Tick-borne'], geographic_distribution: ['east_africa', 'mediterranean', 'usa_south'], regional_prevalence: { east_africa: 0.18, nairobi_ke: 0.18, mediterranean: 0.15, usa_south: 0.08 }, pathognomonic_tests: [{ test: 'serology.ehrlichia_antibody', result: 'positive', probability_if_positive: 0.9, probability_if_negative: 0.05, required_for_confirmation: true }, { test: 'pcr.ehrlichia_pcr', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive Ehrlichia PCR', required_for_confirmation: true }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['thrombocytopenia'], common_signs: ['non_regenerative_anemia', 'hyperglobulinemia', 'fever', 'weight_loss'], rare_signs: ['epistaxis'], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.thrombocytopenia', result: 'present', boost: 0.15, evidence_label: 'Thrombocytopenia' }, { finding: 'cbc.anemia_type', result: 'non_regenerative', boost: 0.1, evidence_label: 'Non-regenerative anemia' }], references: CORE_REFS }),
    buildCondition({ id: 'anaplasmosis_canine', canonical_name: 'Anaplasmosis', aliases: ['Anaplasma phagocytophilum infection', 'Anaplasma platys infection'], species_affected: CANINE, etiological_class: 'parasitic_protozoan', causative_agent: 'Anaplasma phagocytophilum / A. platys', vector: ['Ixodes tick', 'Rhipicephalus tick'], transmission_route: ['Tick-borne'], geographic_distribution: ['east_africa', 'europe', 'usa_northeast'], regional_prevalence: { east_africa: 0.1, europe: 0.06, usa_northeast: 0.1 }, pathognomonic_tests: [{ test: 'serology.anaplasma_antibody', result: 'positive', probability_if_positive: 0.88, probability_if_negative: 0.05, required_for_confirmation: true }, { test: 'pcr.anaplasma_pcr', result: 'positive', probability_if_positive: 0.93, required_for_confirmation: true }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['thrombocytopenia'], common_signs: ['fever', 'weakness', 'lameness'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.thrombocytopenia', result: 'present', boost: 0.15, evidence_label: 'Thrombocytopenia' }], references: CORE_REFS }),
    buildCondition({ id: 'leishmaniosis_canine', canonical_name: 'Leishmaniosis', aliases: ['Canine leishmaniosis'], species_affected: CANINE, etiological_class: 'parasitic_protozoan', causative_agent: 'Leishmania infantum / donovani', vector: ['Phlebotomus sandflies'], transmission_route: ['Vector-borne'], geographic_distribution: ['mediterranean', 'south_america', 'east_africa'], regional_prevalence: { mediterranean: 0.20, south_america: 0.15, east_africa: 0.04, nairobi_ke: 0.03 }, pathognomonic_tests: [{ test: 'serology.leishmania_antibody', result: 'positive', probability_if_positive: 0.9, probability_if_negative: 0.04, required_for_confirmation: true }, { test: 'pcr.leishmania_pcr', result: 'positive', probability_if_positive: 0.94, required_for_confirmation: true }], supporting_tests: [{ test: 'biochemistry.globulins', result: 'hyperglobulinemia', boost: 0.1, evidence_label: 'Hyperglobulinaemia' }, { test: 'biochemistry.albumin', result: 'hypoalbuminemia', boost: 0.08, evidence_label: 'Hypoalbuminaemia' }, { test: 'urinalysis.proteinuria', result: 'present', boost: 0.08, evidence_label: 'Proteinuria' }], exclusion_criteria: [], cardinal_signs: ['weight_loss'], common_signs: ['skin_lesions', 'lymphadenopathy', 'uveitis', 'epistaxis', 'cachexia'], rare_signs: ['polyuria_polydipsia'], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.thrombocytopenia', result: 'present', boost: 0.08, evidence_label: 'Thrombocytopenia' }], references: CORE_REFS }),
    buildCondition({ id: 'leptospirosis', canonical_name: 'Leptospirosis', aliases: [], species_affected: CANINE, etiological_class: 'bacterial', causative_agent: 'Leptospira interrogans serovars', vector: [], transmission_route: ['Contaminated water', 'Wildlife urine exposure'], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.06, nairobi_ke: 0.06 }, pathognomonic_tests: [{ test: 'serology.leptospira_titer', result: 'positive', probability_if_positive: 0.9, required_for_confirmation: true }, { test: 'pcr.leptospira_pcr', result: 'positive', probability_if_positive: 0.94, required_for_confirmation: true }], supporting_tests: [{ test: 'biochemistry.bun_creatinine', result: 'azotemia', boost: 0.18, evidence_label: 'Azotemia' }, { test: 'biochemistry.bilirubin', result: 'elevated', boost: 0.1, evidence_label: 'Hyperbilirubinaemia' }], exclusion_criteria: [], cardinal_signs: ['fever'], common_signs: ['acute_renal_failure', 'jaundice', 'polyuria_polydipsia', 'vomiting'], rare_signs: ['uveitis', 'hemorrhage'], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.thrombocytopenia', result: 'present', boost: 0.06, evidence_label: 'Thrombocytopenia' }], references: CORE_REFS }),
    buildCondition({ id: 'parvoviral_enteritis', canonical_name: 'Parvoviral Enteritis', aliases: ['Canine parvovirus'], species_affected: CANINE, etiological_class: 'viral', causative_agent: 'Canine parvovirus type 2', vector: [], transmission_route: ['Fecal-oral'], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.12, nairobi_ke: 0.12 }, pathognomonic_tests: [{ test: 'serology.parvovirus_antigen', result: 'positive', probability_if_positive: 0.95, required_for_confirmation: true }], supporting_tests: [{ test: 'cbc.lymphopenia', result: 'present', boost: 0.12, evidence_label: 'Lymphopenia' }], exclusion_criteria: [], cardinal_signs: ['vomiting', 'diarrhea'], common_signs: ['bloody_diarrhea', 'dehydration', 'lethargy'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.lymphopenia', result: 'present', boost: 0.15, evidence_label: 'Lymphopenia' }], references: CORE_REFS }),
    buildCondition({ id: 'mitral_valve_disease_canine', canonical_name: 'Mitral Valve Disease', aliases: ['Myxomatous mitral valve disease', 'MMVD'], species_affected: CANINE, etiological_class: 'cardiovascular_structural', causative_agent: 'Degenerative mitral valve disease', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.05 }, pathognomonic_tests: [{ test: 'echocardiography.left_heart_enlargement', result: 'present', probability_if_positive: 0.8 }, { test: 'physical_exam.auscultation.heart_murmur', result: 'grade_3', probability_if_positive: 0.7 }], supporting_tests: [], exclusion_criteria: [{ field: 'thoracic_radiograph.cardiomegaly', expected_value: 'right_sided', explanation: 'Right-sided cardiac enlargement weakens primary mitral disease.', penalty: 0.3 }], cardinal_signs: ['cough'], common_signs: ['exercise_intolerance', 'dyspnea', 'left_heart_enlargement'], rare_signs: ['syncope'], signs_that_exclude: ['right_sided_only_changes'], imaging_patterns: [{ finding: 'thoracic_radiograph.cardiomegaly', result: 'left_sided', boost: 0.2, evidence_label: 'Left-sided cardiomegaly' }], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'dilated_cardiomyopathy_canine', canonical_name: 'Dilated Cardiomyopathy', aliases: ['DCM'], species_affected: CANINE, etiological_class: 'cardiovascular_structural', causative_agent: 'Primary myocardial systolic dysfunction', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [{ test: 'echocardiography.reduced_contractility', result: 'present', probability_if_positive: 0.88 }], supporting_tests: [{ test: 'thoracic_radiograph.cardiomegaly', result: 'generalised', boost: 0.16, evidence_label: 'Generalised cardiomegaly' }], exclusion_criteria: [{ field: 'thoracic_radiograph.cardiomegaly', expected_value: 'right_sided', explanation: 'Isolated right-sided enlargement argues for a pulmonary vascular cause over DCM.', penalty: 0.3 }], cardinal_signs: ['exercise_intolerance'], common_signs: ['cough', 'dyspnea', 'syncope', 'arrhythmia'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [{ finding: 'echocardiography.reduced_contractility', result: 'present', boost: 0.25, evidence_label: 'Reduced contractility' }], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'hyperadrenocorticism_canine', canonical_name: 'Hyperadrenocorticism', aliases: ['Cushings disease'], species_affected: CANINE, etiological_class: 'metabolic_endocrine', causative_agent: 'Excess cortisol', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [{ test: 'serology.ldds_test', result: 'positive', probability_if_positive: 0.9 }, { test: 'serology.acth_stim', result: 'positive', probability_if_positive: 0.86 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['polyuria', 'polydipsia'], common_signs: ['pot_bellied', 'alopecia', 'muscle_weakness'], rare_signs: ['calcinosis_cutis'], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.lymphopenia', result: 'present', boost: 0.08, evidence_label: 'Stress leukogram pattern' }], references: CORE_REFS }),
    buildCondition({ id: 'hypoadrenocorticism_canine', canonical_name: 'Hypoadrenocorticism', aliases: ['Addisons disease'], species_affected: CANINE, etiological_class: 'metabolic_endocrine', causative_agent: 'Cortisol and aldosterone deficiency', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.02 }, pathognomonic_tests: [{ test: 'serology.acth_stim', result: 'flat', probability_if_positive: 0.94 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['weakness'], common_signs: ['vomiting', 'diarrhea', 'shock', 'bradycardia'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.eosinophilia', result: 'present', boost: 0.05, evidence_label: 'Eosinophilia' }], references: CORE_REFS }),
    buildCondition({ id: 'immune_mediated_hemolytic_anemia', canonical_name: 'Immune-mediated Haemolytic Anaemia', aliases: ['IMHA'], species_affected: CANINE, etiological_class: 'immune_mediated', causative_agent: 'Autoimmune hemolysis', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.02 }, pathognomonic_tests: [{ test: 'serology.coombs_test', result: 'positive', probability_if_positive: 0.9 }, { test: 'serology.saline_agglutination', result: 'positive', probability_if_positive: 0.9 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['pallor'], common_signs: ['weakness', 'collapse', 'icterus', 'hemoglobinuria'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.anemia_type', result: 'regenerative', boost: 0.12, evidence_label: 'Regenerative anemia' }], references: CORE_REFS }),
    buildCondition({ id: 'lymphoma', canonical_name: 'Lymphoma', aliases: [], species_affected: CANINE, etiological_class: 'neoplastic', causative_agent: 'Lymphoid neoplasia', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.03 }, pathognomonic_tests: [{ test: 'cytology.lymph_node_fnab', result: 'large_cell_lymphoma', probability_if_positive: 0.95 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['lymphadenopathy'], common_signs: ['weight_loss', 'anorexia', 'fever'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.anemia_type', result: 'non_regenerative', boost: 0.08, evidence_label: 'Non-regenerative anemia' }], references: CORE_REFS }),
    buildCondition({ id: 'gastric_dilatation_volvulus', canonical_name: 'Gastric Dilatation-Volvulus', aliases: ['GDV'], species_affected: CANINE, etiological_class: 'gastrointestinal_structural', causative_agent: 'Gastric dilation with volvulus', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.02 }, pathognomonic_tests: [{ test: 'radiograph.double_bubble_sign', result: 'present', probability_if_positive: 0.98 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['unproductive_retching', 'abdominal_distension'], common_signs: ['shock', 'tachycardia', 'collapse'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'renal_disease_chronic', canonical_name: 'Chronic Kidney Disease', aliases: ['CKD'], species_affected: CANINE, etiological_class: 'metabolic_endocrine', causative_agent: 'Chronic renal insufficiency', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.04 }, pathognomonic_tests: [{ test: 'biochemistry.bun_creatinine', result: 'azotemia', probability_if_positive: 0.7 }, { test: 'urinalysis.specific_gravity', result: 'low', probability_if_positive: 0.8 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['weight_loss'], common_signs: ['polyuria', 'polydipsia', 'vomiting', 'pallor'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'hepatozoonosis', canonical_name: 'Hepatozoonosis', aliases: ['Hepatozoon canis infection'], species_affected: CANINE, etiological_class: 'parasitic_helminth', causative_agent: 'Hepatozoon canis / americanum', vector: ['Rhipicephalus tick', 'Amblyomma tick'], transmission_route: ['Tick ingestion'], geographic_distribution: ['east_africa', 'mediterranean'], regional_prevalence: { east_africa: 0.07, nairobi_ke: 0.06, mediterranean: 0.06 }, pathognomonic_tests: [{ test: 'pcr.hepatozoon_pcr', result: 'positive', probability_if_positive: 0.9 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['fever'], common_signs: ['muscle_pain', 'weakness', 'neutrophilia'], rare_signs: ['periosteal_reaction'], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'trypanosomiasis', canonical_name: 'Trypanosomiasis', aliases: ['African trypanosomiasis'], species_affected: [...CANINE, ...BOVINE], etiological_class: 'parasitic_protozoan', causative_agent: 'Trypanosoma brucei / congolense', vector: ['Glossina tsetse fly'], transmission_route: ['Vector-borne'], geographic_distribution: ['east_africa', 'sub_saharan_africa'], regional_prevalence: { east_africa: 0.05, sub_saharan_africa: 0.08 }, pathognomonic_tests: [{ test: 'pcr.trypanosoma_pcr', result: 'positive', probability_if_positive: 0.92 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['fever'], common_signs: ['anemia', 'cachexia', 'lymphadenopathy', 'neurological_signs'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'toxocariasis', canonical_name: 'Toxocariasis', aliases: ['Toxocara canis infection'], species_affected: CANINE, etiological_class: 'parasitic_helminth', causative_agent: 'Toxocara canis / cati', vector: [], transmission_route: ['Fecal-oral', 'Transplacental'], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.08 }, pathognomonic_tests: [{ test: 'parasitology.fecal_flotation', result: 'toxocara', probability_if_positive: 0.88 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['diarrhea'], common_signs: ['pot_bellied', 'respiratory_signs', 'weight_loss'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.eosinophilia', result: 'present', boost: 0.1, evidence_label: 'Eosinophilia' }], references: CORE_REFS }),
    buildCondition({ id: 'hookworm_infection', canonical_name: 'Hookworm Infection', aliases: ['Ancylostoma infection'], species_affected: CANINE, etiological_class: 'parasitic_helminth', causative_agent: 'Ancylostoma / Uncinaria', vector: [], transmission_route: ['Fecal-oral', 'Percutaneous'], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.07 }, pathognomonic_tests: [{ test: 'parasitology.fecal_flotation', result: 'hookworm', probability_if_positive: 0.88 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['diarrhea'], common_signs: ['melena', 'anemia', 'hypoproteinemia'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.anemia_type', result: 'regenerative', boost: 0.1, evidence_label: 'Regenerative anemia' }], references: CORE_REFS }),
    buildCondition({ id: 'mast_cell_tumor', canonical_name: 'Mast Cell Tumor', aliases: [], species_affected: CANINE, etiological_class: 'neoplastic', causative_agent: 'Mast cell neoplasia', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.02 }, pathognomonic_tests: [{ test: 'cytology.mass_fnab', result: 'mast_cells_granules', probability_if_positive: 0.95 }], supporting_tests: [], exclusion_criteria: [], cardinal_signs: ['skin_mass'], common_signs: ['gastric_ulceration', 'anaphylaxis'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [{ finding: 'cbc.eosinophilia', result: 'present', boost: 0.03, evidence_label: 'Eosinophilia' }], references: CORE_REFS }),
    buildCondition({ id: 'pneumonia_bacterial', canonical_name: 'Bacterial Pneumonia', aliases: [], species_affected: CANINE, etiological_class: 'bacterial', causative_agent: 'Mixed bacterial lower airway infection', vector: [], transmission_route: ['Respiratory'], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.04 }, pathognomonic_tests: [], supporting_tests: [{ test: 'thoracic_radiograph.pulmonary_pattern', result: 'alveolar', boost: 0.22, evidence_label: 'Alveolar pattern' }], exclusion_criteria: [], cardinal_signs: ['cough'], common_signs: ['fever', 'nasal_discharge', 'increased_lung_sounds'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [{ finding: 'thoracic_radiograph.pulmonary_pattern', result: 'alveolar', boost: 0.22, evidence_label: 'Alveolar pattern' }], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'pneumonia_aspiration', canonical_name: 'Aspiration Pneumonia', aliases: [], species_affected: CANINE, etiological_class: 'bacterial', causative_agent: 'Aspiration-associated lower airway disease', vector: [], transmission_route: ['Aspiration'], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.02 }, pathognomonic_tests: [], supporting_tests: [{ test: 'thoracic_radiograph.pulmonary_pattern', result: 'alveolar', boost: 0.18, evidence_label: 'Ventral alveolar pattern' }], exclusion_criteria: [], cardinal_signs: ['acute_respiratory_distress'], common_signs: ['cough', 'fever'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [{ finding: 'thoracic_radiograph.pulmonary_pattern', result: 'alveolar', boost: 0.18, evidence_label: 'Alveolar pattern' }], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({ id: 'protein_losing_enteropathy', canonical_name: 'Protein-losing Enteropathy', aliases: ['PLE'], species_affected: CANINE, etiological_class: 'gastrointestinal_structural', causative_agent: 'Enteric protein loss', vector: [], transmission_route: [], geographic_distribution: ['global'], regional_prevalence: { east_africa: 0.02 }, pathognomonic_tests: [], supporting_tests: [{ test: 'biochemistry.albumin', result: 'hypoalbuminemia', boost: 0.18, evidence_label: 'Hypoalbuminaemia' }], exclusion_criteria: [], cardinal_signs: ['weight_loss'], common_signs: ['diarrhea', 'ascites', 'edema'], rare_signs: [], signs_that_exclude: [], imaging_patterns: [], haematological_patterns: [], references: CORE_REFS }),
    buildCondition({
        id: 'feline_upper_respiratory_complex',
        canonical_name: 'Feline Upper Respiratory Disease Complex',
        aliases: ['FURDC', 'Feline URI complex', 'Feline upper respiratory syndrome'],
        species_affected: FELINE,
        etiological_class: 'viral',
        causative_agent: 'FHV-1, FCV, Chlamydophila felis, Bordetella bronchiseptica, Mycoplasma spp.',
        vector: [],
        transmission_route: ['Direct contact', 'Aerosol', 'Fomite'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.18 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'pcr.fhv_1_pcr', result: 'positive', boost: 0.14, evidence_label: 'Positive FHV-1 PCR' },
            { test: 'pcr.fcv_pcr', result: 'positive', boost: 0.14, evidence_label: 'Positive FCV PCR' },
            { test: 'pcr.chlamydophila_felis_pcr', result: 'positive', boost: 0.12, evidence_label: 'Positive Chlamydophila felis PCR' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['sneezing', 'nasal_discharge_mucopurulent', 'conjunctivitis'],
        common_signs: ['nasal_discharge_serous', 'ocular_discharge', 'fever', 'anorexia', 'lethargy'],
        rare_signs: ['oral_ulceration', 'hypersalivation'],
        signs_that_exclude: ['cyanosis'],
        imaging_patterns: [],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
    buildCondition({
        id: 'feline_herpesvirus_1_infection',
        canonical_name: 'FHV-1 Infection',
        aliases: ['Feline herpesvirus-1 infection', 'FHV-1'],
        species_affected: FELINE,
        etiological_class: 'viral',
        causative_agent: 'Feline herpesvirus-1',
        vector: [],
        transmission_route: ['Direct contact', 'Aerosol'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.12 },
        pathognomonic_tests: [
            { test: 'pcr.fhv_1_pcr', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive FHV-1 PCR', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['conjunctivitis', 'sneezing'],
        common_signs: ['nasal_discharge_serous', 'nasal_discharge_mucopurulent', 'ocular_discharge', 'fever', 'anorexia'],
        rare_signs: ['oral_ulceration'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
    buildCondition({
        id: 'feline_calicivirus_infection',
        canonical_name: 'FCV Infection',
        aliases: ['Feline calicivirus infection', 'FCV'],
        species_affected: FELINE,
        etiological_class: 'viral',
        causative_agent: 'Feline calicivirus',
        vector: [],
        transmission_route: ['Direct contact', 'Aerosol'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.09 },
        pathognomonic_tests: [
            { test: 'pcr.fcv_pcr', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive FCV PCR', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['oral_ulceration', 'hypersalivation'],
        common_signs: ['sneezing', 'nasal_discharge_serous', 'nasal_discharge_mucopurulent', 'fever', 'anorexia'],
        rare_signs: ['ocular_discharge'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
    buildCondition({
        id: 'chlamydophila_felis_upper_respiratory_infection',
        canonical_name: 'Chlamydophila-associated URI',
        aliases: ['Chlamydophila felis URI', 'Chlamydophila felis infection'],
        species_affected: FELINE,
        etiological_class: 'bacterial',
        causative_agent: 'Chlamydophila felis',
        vector: [],
        transmission_route: ['Direct contact', 'Aerosol'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.06 },
        pathognomonic_tests: [
            { test: 'pcr.chlamydophila_felis_pcr', result: 'positive', probability_if_positive: 0.93, evidence_label: 'Positive Chlamydophila felis PCR', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['conjunctivitis', 'ocular_discharge'],
        common_signs: ['sneezing', 'nasal_discharge_serous', 'nasal_discharge_mucopurulent', 'fever'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
    buildCondition({
        id: 'feline_secondary_bacterial_upper_respiratory_infection',
        canonical_name: 'Secondary Bacterial Upper Respiratory Infection',
        aliases: ['Secondary bacterial feline URI'],
        species_affected: FELINE,
        etiological_class: 'bacterial',
        causative_agent: 'Secondary mixed bacterial upper respiratory infection',
        vector: [],
        transmission_route: ['Direct contact', 'Aerosol'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.05 },
        pathognomonic_tests: [],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['nasal_discharge_mucopurulent'],
        common_signs: ['conjunctivitis', 'ocular_discharge', 'sneezing', 'fever', 'lethargy'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
    buildCondition({
        id: 'bordetella_bronchiseptica_feline',
        canonical_name: 'Bordetella Infection',
        aliases: ['Bordetella bronchiseptica feline infection'],
        species_affected: FELINE,
        etiological_class: 'bacterial',
        causative_agent: 'Bordetella bronchiseptica',
        vector: [],
        transmission_route: ['Direct contact', 'Aerosol'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'pcr.bordetella_bronchiseptica_pcr', result: 'positive', probability_if_positive: 0.91, evidence_label: 'Positive Bordetella PCR', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['coughing'],
        common_signs: ['sneezing', 'nasal_discharge_serous', 'dyspnea', 'fever'],
        rare_signs: ['tachypnea'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
    buildCondition({
        id: 'feline_bacterial_pneumonia',
        canonical_name: 'Feline Bacterial Pneumonia',
        aliases: ['Feline pneumonia'],
        species_affected: FELINE,
        etiological_class: 'bacterial',
        causative_agent: 'Mixed bacterial lower airway infection',
        vector: [],
        transmission_route: ['Respiratory'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'thoracic_radiograph.pulmonary_pattern', result: 'alveolar', boost: 0.24, evidence_label: 'Alveolar pattern' },
            { test: 'thoracic_radiograph.pulmonary_pattern', result: 'interstitial', boost: 0.16, evidence_label: 'Interstitial lung pattern' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['dyspnea', 'abnormal_lung_sounds'],
        common_signs: ['tachypnea', 'coughing', 'fever', 'cyanosis'],
        rare_signs: [],
        signs_that_exclude: ['conjunctivitis', 'oral_ulceration', 'hypersalivation'],
        imaging_patterns: [
            { finding: 'thoracic_radiograph.pulmonary_pattern', result: 'alveolar', boost: 0.24, evidence_label: 'Alveolar pattern' },
            { finding: 'thoracic_radiograph.pulmonary_pattern', result: 'interstitial', boost: 0.16, evidence_label: 'Interstitial lung pattern' },
        ],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
    buildCondition({
        id: 'feline_chronic_bronchitis',
        canonical_name: 'Feline Chronic Bronchitis',
        aliases: ['Feline lower airway bronchitis'],
        species_affected: FELINE,
        etiological_class: 'respiratory_structural',
        causative_agent: 'Chronic inflammatory lower airway disease',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'bronchoscopy.bal_neutrophilia', result: 'present', probability_if_positive: 0.84, evidence_label: 'BAL neutrophilic inflammation' },
        ],
        supporting_tests: [
            { test: 'thoracic_radiograph.pulmonary_pattern', result: 'bronchial', boost: 0.18, evidence_label: 'Bronchial lung pattern' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['chronic_cough'],
        common_signs: ['tachypnea', 'abnormal_lung_sounds', 'dyspnea'],
        rare_signs: ['cyanosis'],
        signs_that_exclude: ['conjunctivitis', 'oral_ulceration', 'hypersalivation'],
        imaging_patterns: [
            { finding: 'thoracic_radiograph.pulmonary_pattern', result: 'bronchial', boost: 0.18, evidence_label: 'Bronchial lung pattern' },
        ],
        haematological_patterns: [],
        references: FELINE_URI_REFS,
    }),
];

export function normalizeSpecies(species: string | undefined | null): Species {
    const normalized = String(species ?? 'canine').trim().toLowerCase();
    if (normalized.startsWith('fel') || normalized === 'cat' || normalized === 'cats' || normalized === 'kitten') return 'feline';
    if (normalized.startsWith('bov') || normalized === 'cow') return 'bovine';
    if (normalized.startsWith('ovi') || normalized === 'sheep') return 'ovine';
    if (normalized.startsWith('cap') || normalized === 'goat') return 'caprine';
    if (normalized.startsWith('equ') || normalized === 'horse') return 'equine';
    return 'canine';
}

export function getConditionsForSpecies(species: string | null | undefined): VeterinaryCondition[] {
    const normalized = normalizeSpecies(species);
    return VETERINARY_CONDITIONS.filter((condition) => condition.species_affected.includes(normalized));
}

export function getConditionById(conditionId: string): VeterinaryCondition | undefined {
    return VETERINARY_CONDITIONS.find((condition) => condition.id === conditionId);
}

export function findConditionByName(name: string): VeterinaryCondition | undefined {
    const normalized = name.trim().toLowerCase();
    return VETERINARY_CONDITIONS.find((condition) =>
        condition.canonical_name.toLowerCase() === normalized
        || condition.aliases.some((alias) => alias.toLowerCase() === normalized),
    );
}

// ── GI Conditions: large-bowel colitis, hemorrhagic, peritoneal, pancreatic ──

VETERINARY_CONDITIONS.push(
    buildCondition({
        id: 'clostridial_enterotoxicosis',
        canonical_name: 'Clostridial Enterotoxicosis',
        aliases: ['Clostridiosis', 'Clostridium perfringens enterotoxicosis', 'Clostridium difficile colitis'],
        species_affected: CANINE,
        etiological_class: 'bacterial',
        causative_agent: 'Clostridium perfringens / C. difficile enterotoxin',
        vector: [],
        transmission_route: ['Fecal-oral', 'Contaminated food'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.12, east_africa: 0.10, nairobi_ke: 0.10 },
        pathognomonic_tests: [
            { test: 'serology.clostridium_enterotoxin_elisa', result: 'positive', probability_if_positive: 0.94, probability_if_negative: 0.06, evidence_label: 'Positive Clostridium enterotoxin ELISA', required_for_confirmation: true },
            { test: 'cytology.fecal_gram_positive_rods', result: 'present', probability_if_positive: 0.82, evidence_label: 'Gram-positive rods on fecal cytology' },
        ],
        supporting_tests: [
            { test: 'history.spoiled_meat_ingestion', result: 'confirmed', boost: 0.18, evidence_label: 'Confirmed spoiled meat ingestion' },
            { test: 'history.dietary_indiscretion', result: 'confirmed', boost: 0.12, evidence_label: 'Dietary indiscretion history' },
        ],
        exclusion_criteria: [
            { field: 'serology.parvovirus_antigen', expected_value: 'positive', explanation: 'Positive parvovirus antigen shifts diagnosis away from clostridial enterotoxicosis.', penalty: 0.6 },
            { field: 'physical_exam.peritoneal_signs', expected_value: 'present', explanation: 'Peritoneal signs suggest a different primary diagnosis.', penalty: 0.45 },
            { field: 'physical_exam.shock', expected_value: 'present', explanation: 'Haemodynamic shock alone is not typical of clostridial enterotoxicosis.', penalty: 0.35 },
        ],
        cardinal_signs: ['hematochezia', 'mucus_in_stool', 'tenesmus', 'bloody_diarrhea'],
        common_signs: ['vomiting', 'diarrhea', 'abdominal_pain', 'dehydration'],
        rare_signs: ['fever'],
        signs_that_exclude: ['peritoneal_signs', 'severe_abdominal_distension', 'shock'],
        imaging_patterns: [],
        haematological_patterns: [],
        references: ['WSAVA Global Guidelines', 'Weese et al. Clostridium difficile in companion animals', 'Marks JVIM 2011'],
    }),
    buildCondition({
        id: 'acute_hemorrhagic_diarrhea_syndrome',
        canonical_name: 'Acute Hemorrhagic Diarrhea Syndrome',
        aliases: ['AHDS', 'Hemorrhagic gastroenteritis', 'HGE'],
        species_affected: CANINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Multifactorial — Clostridium perfringens NetF toxin implicated',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.08, east_africa: 0.06, nairobi_ke: 0.06 },
        pathognomonic_tests: [
            { test: 'cbc.packed_cell_volume', result: 'hemoconcentration', probability_if_positive: 0.78, evidence_label: 'Marked hemoconcentration (PCV >60%)' },
        ],
        supporting_tests: [
            { test: 'history.acute_onset', result: 'confirmed', boost: 0.14, evidence_label: 'Acute onset' },
            { test: 'history.no_prior_illness', result: 'confirmed', boost: 0.08, evidence_label: 'No prior GI illness' },
        ],
        exclusion_criteria: [
            { field: 'serology.parvovirus_antigen', expected_value: 'positive', explanation: 'Positive parvo antigen excludes idiopathic AHDS.', penalty: 0.7 },
            { field: 'physical_exam.shock', expected_value: 'severe', explanation: 'Severe shock shifts differential to septic aetiology.', penalty: 0.3 },
        ],
        cardinal_signs: ['bloody_diarrhea', 'hematochezia', 'acute_onset'],
        common_signs: ['vomiting', 'dehydration', 'lethargy', 'anorexia'],
        rare_signs: ['melena'],
        signs_that_exclude: ['peritoneal_signs', 'severe_abdominal_distension'],
        imaging_patterns: [],
        haematological_patterns: [
            { finding: 'cbc.packed_cell_volume', result: 'hemoconcentration', boost: 0.22, evidence_label: 'Hemoconcentration' },
        ],
        references: ['Unterer et al. JVIM 2011', 'WSAVA GI Guidelines'],
    }),
    buildCondition({
        id: 'infectious_colitis',
        canonical_name: 'Infectious Colitis',
        aliases: ['Bacterial colitis', 'Campylobacter colitis', 'Salmonella colitis'],
        species_affected: CANINE,
        etiological_class: 'bacterial',
        causative_agent: 'Campylobacter jejuni / Salmonella spp. / E. coli',
        vector: [],
        transmission_route: ['Fecal-oral', 'Contaminated food', 'Environmental'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.10, east_africa: 0.12, nairobi_ke: 0.12 },
        pathognomonic_tests: [
            { test: 'bacteriology.fecal_culture', result: 'pathogen_isolated', probability_if_positive: 0.88, evidence_label: 'Pathogen isolated on fecal culture' },
        ],
        supporting_tests: [
            { test: 'history.exposure_raw_meat', result: 'confirmed', boost: 0.12, evidence_label: 'Raw/contaminated meat exposure' },
            { test: 'serology.clostridium_enterotoxin_elisa', result: 'positive', boost: 0.15, evidence_label: 'Positive enterotoxin assay' },
        ],
        exclusion_criteria: [
            { field: 'serology.parvovirus_antigen', expected_value: 'positive', explanation: 'Positive parvo antigen excludes simple infectious colitis.', penalty: 0.5 },
        ],
        cardinal_signs: ['hematochezia', 'diarrhea', 'mucus_in_stool'],
        common_signs: ['tenesmus', 'vomiting', 'abdominal_pain', 'dehydration', 'fever'],
        rare_signs: ['systemic_illness'],
        signs_that_exclude: ['peritoneal_signs', 'shock'],
        imaging_patterns: [],
        haematological_patterns: [],
        references: ['WSAVA Global Guidelines', 'Marks 2011 JVIM'],
    }),
    buildCondition({
        id: 'dietary_enterocolitis',
        canonical_name: 'Dietary Enterocolitis',
        aliases: ['Dietary indiscretion colitis', 'Food-induced colitis', 'Garbage gut'],
        species_affected: CANINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Dietary indiscretion / food intolerance',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.15, east_africa: 0.12, nairobi_ke: 0.12 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'history.spoiled_meat_ingestion', result: 'confirmed', boost: 0.24, evidence_label: 'Confirmed spoiled/inappropriate food ingestion' },
            { test: 'history.dietary_indiscretion', result: 'confirmed', boost: 0.18, evidence_label: 'Dietary indiscretion' },
        ],
        exclusion_criteria: [
            { field: 'serology.parvovirus_antigen', expected_value: 'positive', explanation: 'Positive parvovirus displaces dietary diagnosis.', penalty: 0.6 },
            { field: 'physical_exam.shock', expected_value: 'present', explanation: 'Shock not consistent with simple dietary colitis.', penalty: 0.5 },
        ],
        cardinal_signs: ['diarrhea', 'vomiting'],
        common_signs: ['hematochezia', 'mucus_in_stool', 'abdominal_pain', 'dehydration'],
        rare_signs: ['tenesmus'],
        signs_that_exclude: ['shock', 'peritoneal_signs', 'severe_systemic_illness'],
        imaging_patterns: [],
        haematological_patterns: [],
        references: ['WSAVA Global Guidelines'],
    }),
    buildCondition({
        id: 'septic_peritonitis',
        canonical_name: 'Septic Peritonitis',
        aliases: ['Peritonitis'],
        species_affected: CANINE,
        etiological_class: 'bacterial',
        causative_agent: 'Enteric bacterial contamination of peritoneal cavity',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01, east_africa: 0.01 },
        pathognomonic_tests: [
            { test: 'cytology.abdominocentesis', result: 'septic_exudate', probability_if_positive: 0.97, evidence_label: 'Septic exudate on abdominocentesis', required_for_confirmation: true },
            { test: 'cytology.abdominal_fluid_bacteria', result: 'present', probability_if_positive: 0.97, evidence_label: 'Bacteria seen in abdominal fluid cytology', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'physical_exam.peritoneal_signs', result: 'present', boost: 0.35, evidence_label: 'Peritoneal signs on examination' },
            { test: 'physical_exam.abdominal_guarding', result: 'present', boost: 0.28, evidence_label: 'Abdominal guarding' },
        ],
        exclusion_criteria: [
            { field: 'physical_exam.peritoneal_signs', expected_value: 'absent', explanation: 'Absence of peritoneal signs makes septic peritonitis very unlikely.', penalty: 0.75 },
            { field: 'signs.hematochezia_dominant', expected_value: 'present', explanation: 'Hematochezia-dominant presentation without peritoneal signs argues against peritonitis.', penalty: 0.4 },
        ],
        cardinal_signs: ['peritoneal_signs', 'abdominal_guarding', 'shock', 'collapse'],
        common_signs: ['fever', 'vomiting', 'abdominal_pain', 'tachycardia'],
        rare_signs: ['diarrhea'],
        signs_that_exclude: ['hematochezia_without_peritoneal_signs', 'tenesmus_isolated', 'mucus_stool_isolated'],
        imaging_patterns: [
            { finding: 'abdominal_radiograph.free_gas', result: 'present', boost: 0.45, evidence_label: 'Free peritoneal gas' },
            { finding: 'ultrasound.free_fluid', result: 'echogenic', boost: 0.3, evidence_label: 'Echogenic peritoneal fluid' },
        ],
        haematological_patterns: [],
        references: ['WSAVA Global Guidelines', 'Costello et al. JVECC 2004'],
    }),
    buildCondition({
        id: 'acute_pancreatitis',
        canonical_name: 'Acute Pancreatitis',
        aliases: ['Pancreatitis'],
        species_affected: CANINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Pancreatic enzyme autoactivation',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03, east_africa: 0.02, nairobi_ke: 0.02 },
        pathognomonic_tests: [
            { test: 'serology.spec_cpl', result: 'elevated', probability_if_positive: 0.88, evidence_label: 'Elevated Spec cPL', required_for_confirmation: true },
            { test: 'serology.lipase', result: 'markedly_elevated', probability_if_positive: 0.76, evidence_label: 'Markedly elevated lipase' },
        ],
        supporting_tests: [
            { test: 'ultrasound.pancreatic_enlargement', result: 'present', boost: 0.28, evidence_label: 'Pancreatic enlargement on ultrasound' },
            { test: 'history.high_fat_meal', result: 'confirmed', boost: 0.12, evidence_label: 'High fat meal ingestion' },
        ],
        exclusion_criteria: [
            { field: 'physical_exam.tenesmus', expected_value: 'present', explanation: 'Tenesmus is a large-bowel sign inconsistent with pancreatitis as primary diagnosis.', penalty: 0.4 },
            { field: 'signs.hematochezia', expected_value: 'dominant', explanation: 'Hematochezia-dominant presentation argues against isolated pancreatitis.', penalty: 0.45 },
        ],
        cardinal_signs: ['cranial_abdominal_pain', 'vomiting', 'anorexia'],
        common_signs: ['dehydration', 'fever', 'lethargy'],
        rare_signs: ['shock', 'jaundice'],
        signs_that_exclude: ['tenesmus', 'hematochezia_dominant', 'mucus_stool_dominant'],
        imaging_patterns: [
            { finding: 'ultrasound.pancreatic_enlargement', result: 'present', boost: 0.28, evidence_label: 'Pancreatic changes on ultrasound' },
        ],
        haematological_patterns: [],
        references: ['Xenoulis JVIM 2015', 'WSAVA Global Guidelines'],
    }),
    buildCondition({
        id: 'mesenteric_volvulus',
        canonical_name: 'Mesenteric Volvulus',
        aliases: ['Intestinal volvulus', 'Mesenteric torsion'],
        species_affected: CANINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Mesenteric root torsion',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.002 },
        pathognomonic_tests: [
            { test: 'radiograph.stacked_bowel_loops', result: 'present', probability_if_positive: 0.88, evidence_label: 'Stacked bowel loops on radiograph' },
            { test: 'ultrasound.whirlpool_sign', result: 'present', probability_if_positive: 0.92, evidence_label: 'Whirlpool sign on ultrasound', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [
            { field: 'physical_exam.shock', expected_value: 'absent', explanation: 'Mesenteric volvulus invariably causes haemodynamic shock.', penalty: 0.85 },
            { field: 'physical_exam.abdominal_distension', expected_value: 'absent', explanation: 'Absence of abdominal distension makes volvulus very unlikely.', penalty: 0.7 },
        ],
        cardinal_signs: ['shock', 'abdominal_distension', 'collapse', 'acute_abdominal_crisis'],
        common_signs: ['vomiting', 'severe_abdominal_pain'],
        rare_signs: ['diarrhea'],
        signs_that_exclude: ['stable_vital_signs', 'hematochezia_without_shock', 'tenesmus_isolated'],
        imaging_patterns: [
            { finding: 'radiograph.stacked_bowel_loops', result: 'present', boost: 0.40, evidence_label: 'Stacked bowel loops' },
        ],
        haematological_patterns: [],
        references: ['WSAVA Global Guidelines', 'Knell et al. JAVMA 2010'],
    }),
    buildCondition({
        id: 'intestinal_obstruction',
        canonical_name: 'Intestinal Obstruction',
        aliases: ['Mechanical intestinal obstruction', 'Small bowel obstruction', 'Foreign body obstruction'],
        species_affected: CANINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Mechanical obstruction of intestinal lumen',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.02, east_africa: 0.02 },
        pathognomonic_tests: [
            { test: 'radiograph.dilated_bowel_loops', result: 'present', probability_if_positive: 0.82, evidence_label: 'Dilated bowel loops on radiograph' },
            { test: 'ultrasound.foreign_body', result: 'present', probability_if_positive: 0.88, evidence_label: 'Foreign body or obstruction on ultrasound', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'history.foreign_body_ingestion', result: 'confirmed', boost: 0.22, evidence_label: 'Foreign body ingestion history' },
        ],
        exclusion_criteria: [
            { field: 'signs.hematochezia_dominant', expected_value: 'present', explanation: 'Hematochezia-dominant large-bowel presentation argues against mechanical obstruction.', penalty: 0.5 },
            { field: 'physical_exam.tenesmus', expected_value: 'present', explanation: 'Tenesmus indicates large bowel disease, not typical obstruction pattern.', penalty: 0.4 },
        ],
        cardinal_signs: ['persistent_vomiting', 'anorexia'],
        common_signs: ['abdominal_pain', 'dehydration', 'lethargy', 'abdominal_distension'],
        rare_signs: ['diarrhea', 'hematochezia'],
        signs_that_exclude: ['hematochezia_dominant', 'tenesmus_isolated', 'mucus_stool_dominant'],
        imaging_patterns: [
            { finding: 'radiograph.dilated_bowel_loops', result: 'present', boost: 0.35, evidence_label: 'Dilated bowel loops' },
        ],
        haematological_patterns: [],
        references: ['WSAVA Global Guidelines'],
    }),
);

VETERINARY_CONDITIONS.push(
    buildCondition({
        id: 'imha_canine',
        canonical_name: 'Immune-Mediated Haemolytic Anaemia',
        aliases: ['IMHA', 'Immune-mediated hemolytic anemia', 'Immune-mediated haemolytic anaemia'],
        species_affected: CANINE,
        etiological_class: 'immune_mediated',
        causative_agent: 'Antibody-mediated erythrocyte destruction',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.02, east_africa: 0.02, nairobi_ke: 0.02 },
        pathognomonic_tests: [
            { test: 'serology.coombs_test', result: 'positive', probability_if_positive: 0.95, evidence_label: 'Positive Coombs test', required_for_confirmation: true },
            { test: 'cbc.autoagglutination', result: 'positive', probability_if_positive: 0.96, evidence_label: 'Positive autoagglutination', required_for_confirmation: true },
            { test: 'cbc.spherocytes', result: 'present', probability_if_positive: 0.94, evidence_label: 'Spherocytes present on blood smear', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cbc.anemia_type', result: 'regenerative', boost: 0.18, evidence_label: 'Regenerative anaemia' },
            { test: 'serology.saline_agglutination', result: 'positive', boost: 0.22, evidence_label: 'Positive saline agglutination' },
        ],
        exclusion_criteria: [
            { field: 'serology.tick_borne_disease_panel', expected_value: 'positive', explanation: 'Positive tick-borne testing requires infectious haemolysis adjudication before primary IMHA is accepted.', penalty: 0.3 },
        ],
        cardinal_signs: ['pale_mucous_membranes', 'weakness'],
        common_signs: ['lethargy', 'collapse', 'icterus', 'hemoglobinuria'],
        rare_signs: ['thromboembolism'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [
            { finding: 'cbc.spherocytes', result: 'present', boost: 0.35, evidence_label: 'Spherocytosis' },
            { finding: 'cbc.autoagglutination', result: 'positive', boost: 0.40, evidence_label: 'Autoagglutination' },
        ],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'imtp_canine',
        canonical_name: 'Immune-Mediated Thrombocytopenia',
        aliases: ['IMTP', 'Immune-mediated platelet destruction'],
        species_affected: CANINE,
        etiological_class: 'immune_mediated',
        causative_agent: 'Antibody-mediated platelet destruction',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.02, east_africa: 0.02 },
        pathognomonic_tests: [
            { test: 'cbc.platelet_count', result: 'severe_thrombocytopenia', probability_if_positive: 0.92, evidence_label: 'Severe thrombocytopenia', required_for_confirmation: true },
            { test: 'serology.antiplatelet_antibody', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive antiplatelet antibody test', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['petechiae', 'ecchymosis'],
        common_signs: ['bleeding', 'melena', 'epistaxis'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [
            { finding: 'cbc.thrombocytopenia', result: 'severe', boost: 0.24, evidence_label: 'Severe thrombocytopenia' },
        ],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'evans_syndrome',
        canonical_name: 'Evans Syndrome',
        aliases: ['IMHA with IMTP'],
        species_affected: CANINE,
        etiological_class: 'immune_mediated',
        causative_agent: 'Concurrent immune-mediated erythrocyte and platelet destruction',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01 },
        pathognomonic_tests: [],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['pale_mucous_membranes', 'petechiae'],
        common_signs: ['weakness', 'bleeding'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'immune_mediated_thrombocytopenia',
        canonical_name: 'Immune-Mediated Thrombocytopenia',
        aliases: ['IMTP'],
        species_affected: CANINE,
        etiological_class: 'immune_mediated',
        causative_agent: 'Antibody-mediated platelet destruction',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.02 },
        pathognomonic_tests: [],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['petechiae'],
        common_signs: ['bleeding'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'feline_infectious_peritonitis',
        canonical_name: 'Feline Infectious Peritonitis',
        aliases: ['FIP'],
        species_affected: FELINE,
        etiological_class: 'viral',
        causative_agent: 'Feline coronavirus-associated immune-mediated vasculitis',
        vector: [],
        transmission_route: ['Fecal-oral coronavirus exposure'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03, east_africa: 0.02 },
        pathognomonic_tests: [
            { test: 'serology.fcov_antibody_titre', result: 'high_positive', probability_if_positive: 0.9, evidence_label: 'High positive FCoV antibody titre', required_for_confirmation: true },
            { test: 'cytology.effusion_rivalta', result: 'positive', probability_if_positive: 0.9, evidence_label: 'Positive Rivalta test', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['effusion', 'fever'],
        common_signs: ['weight_loss', 'lethargy', 'uveitis', 'neurologic_signs'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'addisons_canine',
        canonical_name: 'Hypoadrenocorticism',
        aliases: ['Addisons disease', "Addison's disease"],
        species_affected: CANINE,
        etiological_class: 'metabolic_endocrine',
        causative_agent: 'Cortisol and aldosterone deficiency',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01, east_africa: 0.02 },
        pathognomonic_tests: [
            { test: 'biochemistry.sodium_potassium_ratio', result: 'low', probability_if_positive: 0.88, evidence_label: 'Low sodium:potassium ratio', required_for_confirmation: true },
            { test: 'serology.sodium_potassium_ratio', result: 'low', probability_if_positive: 0.88, evidence_label: 'Low sodium:potassium ratio', required_for_confirmation: true },
            { test: 'serology.acth_stimulation', result: 'flat_response', probability_if_positive: 0.97, evidence_label: 'Flat ACTH stimulation response', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['collapse', 'weakness'],
        common_signs: ['vomiting', 'diarrhea', 'dehydration', 'bradycardia'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'diabetes_mellitus_feline',
        canonical_name: 'Feline Diabetes Mellitus',
        aliases: ['Diabetes mellitus feline', 'Feline diabetes'],
        species_affected: FELINE,
        etiological_class: 'metabolic_endocrine',
        causative_agent: 'Insulin resistance or impaired insulin secretion',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'biochemistry.glucose', result: 'hyperglycemia', probability_if_positive: 0.88, evidence_label: 'Persistent hyperglycaemia', required_for_confirmation: true },
            { test: 'urinalysis.glucose_in_urine', result: 'present', probability_if_positive: 0.88, evidence_label: 'Glucosuria', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['polyuria', 'polydipsia'],
        common_signs: ['weight_loss', 'polyphagia'],
        rare_signs: ['ketosis'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'leptospirosis_canine',
        canonical_name: 'Leptospirosis',
        aliases: ['Canine leptospirosis'],
        species_affected: CANINE,
        etiological_class: 'bacterial',
        causative_agent: 'Leptospira interrogans serovars',
        vector: [],
        transmission_route: ['Contaminated water', 'Wildlife urine exposure'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.04, east_africa: 0.06, nairobi_ke: 0.06 },
        pathognomonic_tests: [
            { test: 'serology.mat_leptospira', result: 'positive', probability_if_positive: 0.92, evidence_label: 'Positive Leptospira MAT', required_for_confirmation: true },
            { test: 'pcr.leptospira_pcr', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive Leptospira PCR', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['fever'],
        common_signs: ['acute_renal_failure', 'jaundice', 'vomiting'],
        rare_signs: ['uveitis'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'toxoplasmosis_canine_feline',
        canonical_name: 'Toxoplasmosis',
        aliases: ['Toxoplasma gondii infection'],
        species_affected: [...CANINE, ...FELINE],
        etiological_class: 'parasitic_protozoan',
        causative_agent: 'Toxoplasma gondii',
        vector: [],
        transmission_route: ['Ingestion of oocysts or tissue cysts'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'serology.toxoplasma_igm', result: 'positive', probability_if_positive: 0.9, evidence_label: 'Positive Toxoplasma IgM', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['neurologic_signs'],
        common_signs: ['uveitis', 'fever', 'respiratory_signs'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'canine_distemper',
        canonical_name: 'Canine Distemper',
        aliases: ['Distemper'],
        species_affected: CANINE,
        etiological_class: 'viral',
        causative_agent: 'Canine distemper virus',
        vector: [],
        transmission_route: ['Respiratory secretions'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03, east_africa: 0.04 },
        pathognomonic_tests: [
            { test: 'serology.distemper_antigen', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive distemper antigen', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['neurologic_signs', 'respiratory_signs'],
        common_signs: ['fever', 'ocular_discharge', 'nasal_discharge', 'myoclonus'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'feline_hyperthyroidism',
        canonical_name: 'Feline Hyperthyroidism',
        aliases: ['Hyperthyroidism feline'],
        species_affected: FELINE,
        etiological_class: 'metabolic_endocrine',
        causative_agent: 'Functional thyroid adenomatous hyperplasia or adenoma',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.1 },
        pathognomonic_tests: [
            { test: 'serology.total_t4_feline', result: 'elevated', probability_if_positive: 0.94, evidence_label: 'Elevated feline total T4', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['weight_loss', 'polyphagia'],
        common_signs: ['tachycardia', 'hypertension', 'vomiting'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'gdv_canine',
        canonical_name: 'Gastric Dilatation-Volvulus',
        aliases: ['GDV', 'Gastric volvulus'],
        species_affected: CANINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Gastric dilation with volvulus',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01 },
        pathognomonic_tests: [
            { test: 'thoracic_radiograph.gastric_volvulus', result: 'present', probability_if_positive: 0.98, evidence_label: 'Radiographic gastric volvulus', required_for_confirmation: true },
            { test: 'imaging.thoracic_radiograph', result: 'gastric_volvulus', probability_if_positive: 0.96, evidence_label: 'Radiographic gastric volvulus', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['retching_unproductive', 'abdominal_distension'],
        common_signs: ['shock', 'tachycardia', 'collapse'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'acute_pancreatitis_canine',
        canonical_name: 'Acute Pancreatitis',
        aliases: ['Canine acute pancreatitis', 'Pancreatitis'],
        species_affected: CANINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Pancreatic enzyme autoactivation',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'serology.pancreatic_lipase', result: 'elevated', probability_if_positive: 0.88, evidence_label: 'Elevated pancreatic lipase', required_for_confirmation: true },
            { test: 'serology.pancreatic_lipase', result: 'markedly_elevated', probability_if_positive: 0.92, evidence_label: 'Markedly elevated pancreatic lipase', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['vomiting', 'abdominal_pain'],
        common_signs: ['anorexia', 'lethargy', 'fever'],
        rare_signs: ['shock'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'pyometra_canine_feline',
        canonical_name: 'Pyometra',
        aliases: ['Uterine infection'],
        species_affected: [...CANINE, ...FELINE],
        etiological_class: 'bacterial',
        causative_agent: 'Ascending bacterial uterine infection',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'abdominal_ultrasound.uterine_distension', result: 'present', probability_if_positive: 0.94, evidence_label: 'Uterine distension on ultrasound', required_for_confirmation: true },
            { test: 'imaging.abdominal_ultrasound', result: 'uterine_distension', probability_if_positive: 0.92, evidence_label: 'Uterine distension on ultrasound', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['vaginal_discharge', 'intact_female'],
        common_signs: ['fever', 'lethargy', 'vomiting', 'polydipsia'],
        rare_signs: ['shock'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
    buildCondition({
        id: 'upper_urinary_tract_obstruction_feline',
        canonical_name: 'Feline Urethral Obstruction',
        aliases: ['Upper urinary tract obstruction feline', 'Feline urethral obstruction'],
        species_affected: FELINE,
        etiological_class: 'idiopathic',
        causative_agent: 'Obstructive uropathy',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'urinalysis.obstructive_pattern', result: 'present', probability_if_positive: 0.95, evidence_label: 'Obstructive urinary pattern', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['stranguria', 'anuria'],
        common_signs: ['vocalisation', 'collapse', 'hyperkalaemia'],
        rare_signs: [],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: CORE_REFS,
    }),
);
