import { getTreatmentProtocolsForCondition } from '../treatment/treatment-registry';
import type { Species, VeterinaryCondition } from './types';

const EQUINE: Species[] = ['equine'];
const EQUINE_REFS = [
    'AAEP equine infectious and emergency care references',
    'Merck Veterinary Manual equine disease references',
    'Peer-reviewed equine internal medicine literature',
];

function condition(input: Omit<VeterinaryCondition, 'treatments'>): VeterinaryCondition {
    return {
        ...input,
        treatments: getTreatmentProtocolsForCondition(input.id),
    };
}

export const EQUINE_CONDITIONS: VeterinaryCondition[] = [
    condition({
        id: 'equine_infectious_anemia',
        canonical_name: 'Equine Infectious Anaemia',
        aliases: ['EIA', 'Swamp fever', 'Equine infectious anemia'],
        species_affected: EQUINE,
        etiological_class: 'viral',
        causative_agent: 'Equine infectious anaemia virus',
        vector: ['Biting flies'],
        transmission_route: ['Blood-borne', 'Vector-borne', 'Iatrogenic blood transfer'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01 },
        pathognomonic_tests: [
            { test: 'serology.coggins_result', result: 'positive', probability_if_positive: 0.96, evidence_label: 'Positive Coggins/EIA test', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [
            { field: 'serology.coggins_result', expected_value: 'negative', explanation: 'Negative Coggins/EIA testing lowers immediate EIA probability.', penalty: 0.6 },
        ],
        cardinal_signs: ['fever', 'anemia'],
        common_signs: ['weight_loss', 'ventral_edema', 'lethargy'],
        rare_signs: ['thrombocytopenia'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: EQUINE_REFS,
    }),
    condition({
        id: 'equine_strangles',
        canonical_name: 'Equine Strangles',
        aliases: ['Streptococcus equi infection', 'Strangles'],
        species_affected: EQUINE,
        etiological_class: 'bacterial',
        causative_agent: 'Streptococcus equi subspecies equi',
        vector: [],
        transmission_route: ['Direct contact', 'Fomite', 'Respiratory secretion'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'pcr.strep_equi_pcr', result: 'positive', probability_if_positive: 0.95, evidence_label: 'Positive Strep equi PCR', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'microbiology.organism', boost: 0.18, evidence_label: 'Streptococcus equi cultured or identified' },
            { test: 'biochemistry.saa_level', result: 'elevated', boost: 0.08, evidence_label: 'Elevated SAA' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['lymphadenopathy', 'fever'],
        common_signs: ['nasal_discharge', 'dysphagia', 'cough', 'lethargy'],
        rare_signs: ['purpura_hemorrhagica'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: EQUINE_REFS,
    }),
    condition({
        id: 'equine_pleuropneumonia',
        canonical_name: 'Equine Pleuropneumonia',
        aliases: ['Pleuropneumonia', 'Equine bacterial pneumonia with pleuritis'],
        species_affected: EQUINE,
        etiological_class: 'bacterial',
        causative_agent: 'Mixed bacterial lower respiratory and pleural infection',
        vector: [],
        transmission_route: ['Respiratory', 'Aspiration-associated risk'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.02 },
        pathognomonic_tests: [
            { test: 'cytology.septic_exudate', result: 'present', probability_if_positive: 0.9, evidence_label: 'Septic pleural exudate', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'thoracic_radiograph.pleural_effusion', result: 'present', boost: 0.22, evidence_label: 'Pleural effusion' },
            { test: 'thoracic_radiograph.pulmonary_infiltrates', result: 'present', boost: 0.18, evidence_label: 'Pulmonary infiltrates' },
            { test: 'biochemistry.saa_level', result: 'elevated', boost: 0.1, evidence_label: 'Elevated SAA' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['fever', 'respiratory_distress'],
        common_signs: ['cough', 'nasal_discharge', 'pleural_effusion', 'lethargy'],
        rare_signs: ['colic'],
        signs_that_exclude: [],
        imaging_patterns: [
            { finding: 'thoracic_radiograph.pleural_effusion', result: 'present', boost: 0.22, evidence_label: 'Pleural effusion' },
            { finding: 'thoracic_radiograph.pulmonary_infiltrates', result: 'present', boost: 0.18, evidence_label: 'Pulmonary infiltrates' },
        ],
        haematological_patterns: [],
        references: EQUINE_REFS,
    }),
    condition({
        id: 'equine_septic_peritonitis',
        canonical_name: 'Equine Septic Peritonitis',
        aliases: ['Septic peritonitis in horses'],
        species_affected: EQUINE,
        etiological_class: 'bacterial',
        causative_agent: 'Bacterial contamination or translocation into the peritoneal cavity',
        vector: [],
        transmission_route: ['Surgical complication', 'Gastrointestinal compromise', 'Penetrating wound'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01 },
        pathognomonic_tests: [
            { test: 'cytology.abdominal_fluid_bacteria', result: 'present', probability_if_positive: 0.96, evidence_label: 'Intracellular abdominal fluid bacteria', required_for_confirmation: true },
            { test: 'cytology.septic_exudate', result: 'present', probability_if_positive: 0.9, evidence_label: 'Septic abdominal exudate', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'abdominal_ultrasound.free_fluid', result: 'present', boost: 0.18, evidence_label: 'Abdominal free fluid' },
            { test: 'biochemistry.saa_level', result: 'elevated', boost: 0.12, evidence_label: 'Elevated SAA' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['colic', 'fever'],
        common_signs: ['abdominal_pain', 'lethargy', 'anorexia', 'tachycardia'],
        rare_signs: ['shock'],
        signs_that_exclude: [],
        imaging_patterns: [
            { finding: 'abdominal_ultrasound.free_fluid', result: 'present', boost: 0.18, evidence_label: 'Abdominal free fluid' },
        ],
        haematological_patterns: [],
        references: EQUINE_REFS,
    }),
    condition({
        id: 'equine_colic_strangulating',
        canonical_name: 'Equine Colic - Strangulating / Surgical Pattern',
        aliases: ['Strangulating colic', 'Surgical colic'],
        species_affected: EQUINE,
        etiological_class: 'gastrointestinal_structural',
        causative_agent: 'Mechanical intestinal obstruction, displacement, strangulation, or ischemia',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.04 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'abdominal_ultrasound.free_fluid', result: 'present', boost: 0.12, evidence_label: 'Abdominal free fluid' },
            { test: 'biochemistry.saa_level', result: 'elevated', boost: 0.08, evidence_label: 'Inflammatory SAA response' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['colic', 'abdominal_pain'],
        common_signs: ['tachycardia', 'anorexia', 'dehydration', 'abdominal_distension'],
        rare_signs: ['shock'],
        signs_that_exclude: [],
        imaging_patterns: [
            { finding: 'abdominal_ultrasound.free_fluid', result: 'present', boost: 0.12, evidence_label: 'Abdominal free fluid' },
        ],
        haematological_patterns: [],
        references: EQUINE_REFS,
    }),
    condition({
        id: 'equine_laminitis',
        canonical_name: 'Equine Laminitis',
        aliases: ['Founder'],
        species_affected: EQUINE,
        etiological_class: 'metabolic_endocrine',
        causative_agent: 'Lamellar inflammation and failure often associated with endocrine, inflammatory, or mechanical triggers',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.04 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'biochemistry.saa_level', result: 'elevated', boost: 0.04, evidence_label: 'Inflammatory trigger signal' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['lameness'],
        common_signs: ['reluctance_to_move', 'increased_digital_pulse', 'foot_pain'],
        rare_signs: ['recumbency'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: EQUINE_REFS,
    }),
];
