import { getTreatmentProtocolsForCondition } from '../treatment/treatment-registry';
import type { Species, VeterinaryCondition } from './types';

const BOVINE: Species[] = ['bovine'];
const RUMINANT: Species[] = ['bovine', 'ovine', 'caprine'];
const RUMINANT_REFS = [
    'WOAH terrestrial animal health guidance',
    'Merck Veterinary Manual food-animal disease references',
    'Peer-reviewed ruminant herd health literature',
];

function condition(input: Omit<VeterinaryCondition, 'treatments'>): VeterinaryCondition {
    return {
        ...input,
        treatments: getTreatmentProtocolsForCondition(input.id),
    };
}

export const RUMINANT_CONDITIONS: VeterinaryCondition[] = [
    condition({
        id: 'bovine_ketosis',
        canonical_name: 'Bovine Ketosis',
        aliases: ['Dairy cow ketosis', 'Hyperketonemia'],
        species_affected: BOVINE,
        etiological_class: 'metabolic_endocrine',
        causative_agent: 'Negative energy balance with elevated ketone bodies',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.08 },
        pathognomonic_tests: [
            { test: 'biochemistry.bhba', result: 'elevated', probability_if_positive: 0.9, evidence_label: 'Elevated BHBA', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'biochemistry.nefa', result: 'elevated', boost: 0.16, evidence_label: 'Elevated NEFA' },
            { test: 'biochemistry.glucose', result: 'hypoglycemia', boost: 0.12, evidence_label: 'Hypoglycaemia' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['anorexia', 'reduced_milk_yield'],
        common_signs: ['weight_loss', 'lethargy', 'decreased_appetite'],
        rare_signs: ['neurologic_signs'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'ruminant_hypocalcemia',
        canonical_name: 'Ruminant Hypocalcaemia / Milk Fever',
        aliases: ['Milk fever', 'Parturient paresis', 'Periparturient hypocalcemia'],
        species_affected: RUMINANT,
        etiological_class: 'metabolic_endocrine',
        causative_agent: 'Periparturient calcium homeostasis failure',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.04 },
        pathognomonic_tests: [
            { test: 'biochemistry.calcium', result: 'low', probability_if_positive: 0.88, evidence_label: 'Low serum calcium', required_for_confirmation: true },
            { test: 'biochemistry.calcium', result: 'hypocalcemia', probability_if_positive: 0.9, evidence_label: 'Hypocalcaemia', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'biochemistry.phosphorus', result: 'low', boost: 0.08, evidence_label: 'Low phosphorus' },
            { test: 'biochemistry.magnesium', result: 'low', boost: 0.08, evidence_label: 'Low magnesium' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['recumbency', 'weakness'],
        common_signs: ['lethargy', 'cold_extremities', 'reduced_rumen_motility'],
        rare_signs: ['collapse'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'ruminant_mastitis',
        canonical_name: 'Ruminant Mastitis',
        aliases: ['Bovine mastitis', 'Clinical mastitis', 'Subclinical mastitis'],
        species_affected: RUMINANT,
        etiological_class: 'bacterial',
        causative_agent: 'Intramammary bacterial infection or inflammation',
        vector: [],
        transmission_route: ['Milking hygiene', 'Environmental exposure', 'Contagious udder pathogen spread'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.12 },
        pathognomonic_tests: [
            { test: 'cytology.california_mastitis_test', result: 'positive', probability_if_positive: 0.82, evidence_label: 'Positive California Mastitis Test', required_for_confirmation: true },
            { test: 'cytology.milk_culture_growth', result: 'present', probability_if_positive: 0.9, evidence_label: 'Milk culture growth', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cytology.somatic_cell_count', boost: 0.18, evidence_label: 'Elevated somatic cell count' },
            { test: 'cytology.bulk_tank_scc', boost: 0.12, evidence_label: 'Elevated bulk tank SCC' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['abnormal_milk', 'udder_swelling'],
        common_signs: ['fever', 'reduced_milk_yield', 'lethargy'],
        rare_signs: ['shock'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'bovine_viral_diarrhea',
        canonical_name: 'Bovine Viral Diarrhoea',
        aliases: ['BVD', 'Bovine viral diarrhea'],
        species_affected: BOVINE,
        etiological_class: 'viral',
        causative_agent: 'Bovine viral diarrhoea virus',
        vector: [],
        transmission_route: ['Direct contact', 'Persistently infected animal exposure', 'Transplacental'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.05 },
        pathognomonic_tests: [
            { test: 'serology.bvd_antigen', result: 'positive', probability_if_positive: 0.9, evidence_label: 'Positive BVD antigen', required_for_confirmation: true },
            { test: 'pcr.bvd_pcr', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive BVD PCR', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cbc.left_shift', result: 'present', boost: 0.06, evidence_label: 'Inflammatory leukogram' },
        ],
        exclusion_criteria: [
            { field: 'serology.bvd_antigen', expected_value: 'negative', explanation: 'Negative BVD antigen lowers immediate BVD probability; repeat testing remains context-specific.', penalty: 0.45 },
        ],
        cardinal_signs: ['diarrhea', 'herd_outbreak'],
        common_signs: ['fever', 'oral_ulceration', 'reproductive_loss', 'poor_growth'],
        rare_signs: ['mucosal_disease'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'lumpy_skin_disease_bovine',
        canonical_name: 'Lumpy Skin Disease',
        aliases: ['LSD', 'Capripoxvirus lumpy skin disease'],
        species_affected: BOVINE,
        etiological_class: 'viral',
        causative_agent: 'Lumpy skin disease virus',
        vector: ['Biting insects'],
        transmission_route: ['Vector-borne', 'Direct contact'],
        geographic_distribution: ['africa', 'middle_east', 'asia', 'europe'],
        regional_prevalence: { global: 0.01, east_africa: 0.05 },
        pathognomonic_tests: [
            { test: 'pcr.lumpy_skin_disease_pcr', result: 'positive', probability_if_positive: 0.96, evidence_label: 'Positive lumpy skin disease PCR', required_for_confirmation: true },
            { test: 'serology.lumpy_skin_disease_pcr', result: 'positive', probability_if_positive: 0.92, evidence_label: 'Positive lumpy skin disease PCR', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['skin_nodules', 'fever'],
        common_signs: ['lymphadenopathy', 'reduced_milk_yield', 'lameness'],
        rare_signs: ['oral_ulceration'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'foot_and_mouth_disease',
        canonical_name: 'Foot-and-Mouth Disease',
        aliases: ['FMD'],
        species_affected: RUMINANT,
        etiological_class: 'viral',
        causative_agent: 'Foot-and-mouth disease virus',
        vector: [],
        transmission_route: ['Direct contact', 'Aerosol', 'Fomite'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.01 },
        pathognomonic_tests: [
            { test: 'serology.fmd_screen', result: 'positive', probability_if_positive: 0.92, evidence_label: 'Positive FMD screen', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [
            { field: 'serology.fmd_screen', expected_value: 'negative', explanation: 'Negative screening lowers FMD probability when compatible lesions are absent.', penalty: 0.5 },
        ],
        cardinal_signs: ['oral_ulceration', 'lameness'],
        common_signs: ['fever', 'salivation', 'herd_outbreak', 'reduced_milk_yield'],
        rare_signs: ['sudden_death_youngstock'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'bovine_theileriosis',
        canonical_name: 'Bovine Theileriosis',
        aliases: ['East Coast fever', 'Theileria infection'],
        species_affected: BOVINE,
        etiological_class: 'parasitic_protozoan',
        causative_agent: 'Theileria spp.',
        vector: ['Ixodid ticks'],
        transmission_route: ['Tick-borne'],
        geographic_distribution: ['east_africa', 'sub_saharan_africa', 'asia'],
        regional_prevalence: { east_africa: 0.08, sub_saharan_africa: 0.05 },
        pathognomonic_tests: [
            { test: 'pcr.theileria_pcr', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive Theileria PCR', required_for_confirmation: true },
            { test: 'serology.theileria_screen', result: 'positive', probability_if_positive: 0.84, evidence_label: 'Positive Theileria screen', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cbc.hemoparasites_seen', boost: 0.18, evidence_label: 'Haemoparasites seen' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['fever', 'lymphadenopathy'],
        common_signs: ['anorexia', 'respiratory_distress', 'anemia', 'tick_exposure'],
        rare_signs: ['neurologic_signs'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'bovine_anaplasmosis',
        canonical_name: 'Bovine Anaplasmosis',
        aliases: ['Anaplasma marginale infection'],
        species_affected: BOVINE,
        etiological_class: 'bacterial',
        causative_agent: 'Anaplasma marginale',
        vector: ['Ticks', 'Mechanical biting flies'],
        transmission_route: ['Vector-borne', 'Iatrogenic blood transfer'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.04, east_africa: 0.06 },
        pathognomonic_tests: [
            { test: 'pcr.anaplasma_marginale_pcr', result: 'positive', probability_if_positive: 0.94, evidence_label: 'Positive Anaplasma marginale PCR', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cbc.hemoparasites_seen', boost: 0.16, evidence_label: 'Haemoparasites seen' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['anemia', 'icterus'],
        common_signs: ['fever', 'weakness', 'tick_exposure', 'reduced_milk_yield'],
        rare_signs: ['aggression'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'johnes_disease_ruminant',
        canonical_name: "Johne's Disease",
        aliases: ['Paratuberculosis', 'Mycobacterium avium subspecies paratuberculosis'],
        species_affected: RUMINANT,
        etiological_class: 'bacterial',
        causative_agent: 'Mycobacterium avium subspecies paratuberculosis',
        vector: [],
        transmission_route: ['Fecal-oral', 'Milk or colostrum exposure'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.03 },
        pathognomonic_tests: [
            { test: 'serology.johnes_elisa', result: 'positive', probability_if_positive: 0.86, evidence_label: 'Positive Johne ELISA', required_for_confirmation: true },
        ],
        supporting_tests: [],
        exclusion_criteria: [],
        cardinal_signs: ['chronic_diarrhea', 'weight_loss'],
        common_signs: ['poor_body_condition', 'reduced_milk_yield'],
        rare_signs: ['bottle_jaw'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'ruminal_acidosis',
        canonical_name: 'Ruminal Acidosis',
        aliases: ['Subacute ruminal acidosis', 'SARA', 'Acute rumen acidosis'],
        species_affected: RUMINANT,
        etiological_class: 'nutritional',
        causative_agent: 'Excess fermentable carbohydrate load with reduced rumen pH',
        vector: [],
        transmission_route: [],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.05 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'biochemistry.rumen_ph', boost: 0.24, evidence_label: 'Low rumen pH' },
            { test: 'abdominal_ultrasound.forestomach_motility', result: 'low', boost: 0.08, evidence_label: 'Reduced forestomach motility' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['rumen_stasis', 'diarrhea'],
        common_signs: ['anorexia', 'dehydration', 'lameness', 'reduced_milk_yield'],
        rare_signs: ['recumbency'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'ruminant_parasitic_gastroenteritis',
        canonical_name: 'Ruminant Parasitic Gastroenteritis',
        aliases: ['GI nematodiasis', 'Haemonchosis risk'],
        species_affected: RUMINANT,
        etiological_class: 'parasitic_helminth',
        causative_agent: 'Gastrointestinal nematodes and coccidia-associated enteric burden',
        vector: [],
        transmission_route: ['Pasture exposure', 'Fecal-oral'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.08, east_africa: 0.12 },
        pathognomonic_tests: [],
        supporting_tests: [
            { test: 'parasitology.fecal_egg_count', boost: 0.18, evidence_label: 'Elevated fecal egg count' },
            { test: 'parasitology.liver_fluke', result: 'positive', boost: 0.14, evidence_label: 'Positive liver fluke test' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['diarrhea', 'weight_loss'],
        common_signs: ['anemia', 'bottle_jaw', 'poor_growth'],
        rare_signs: ['collapse'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
    condition({
        id: 'neonatal_calf_enteritis',
        canonical_name: 'Neonatal Calf / Small Ruminant Enteritis',
        aliases: ['Calf scours', 'Neonatal diarrhea complex'],
        species_affected: RUMINANT,
        etiological_class: 'bacterial',
        causative_agent: 'Multifactorial neonatal enteric infection and failed passive transfer risk',
        vector: [],
        transmission_route: ['Fecal-oral', 'Environmental contamination'],
        geographic_distribution: ['global'],
        regional_prevalence: { global: 0.08 },
        pathognomonic_tests: [
            { test: 'serology.cryptosporidium', result: 'positive', probability_if_positive: 0.82, evidence_label: 'Positive Cryptosporidium test', required_for_confirmation: true },
            { test: 'serology.e_coli_k99', result: 'positive', probability_if_positive: 0.84, evidence_label: 'Positive E. coli K99 test', required_for_confirmation: true },
        ],
        supporting_tests: [
            { test: 'cbc.igg_transfer_status', result: 'low', boost: 0.14, evidence_label: 'Failed or partial passive transfer' },
            { test: 'biochemistry.glucose', result: 'hypoglycemia', boost: 0.08, evidence_label: 'Hypoglycaemia' },
        ],
        exclusion_criteria: [],
        cardinal_signs: ['diarrhea', 'dehydration'],
        common_signs: ['weakness', 'lethargy', 'hypoglycemia', 'poor_suck'],
        rare_signs: ['sepsis'],
        signs_that_exclude: [],
        imaging_patterns: [],
        haematological_patterns: [],
        references: RUMINANT_REFS,
    }),
];
